import type { Lecture } from "@/lib/lectures/types";

const notes = (
	say: string,
	transition: string,
	ask?: string,
	expected?: string,
) => ({ say, transition, ask, expected });

export const blockchainLecture: Lecture = {
	slug: "blockchain-finance-supply-chain",
	shortTitle: "Blockchain: Finance, Supply Chain & Beyond",
	title: "Blockchain Applications in Finance, Supply Chain & Beyond",
	description:
		"A founder-engineered 60-minute interactive technology experience connecting cryptographic foundations, Web3, real 2026 enterprise architectures, and the emerging AI-agent economy.",
	audience: "BCA 1st Year · Kristu Jayanti University, Bengaluru",
	presenter: "Manoj Mukherjee · Founder · AI Scientist · Enterprise AI Architect",
	totalMinutes: 60,
	sources: [
		{
			id: "nist-blockchain",
			label: "Blockchain Architecture and Security Overview",
			publisher: "US National Institute of Standards and Technology (NIST)",
			url: "https://www.nist.gov/blockchain",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "nist-fit",
			label: "Privacy-Enhancing Lightweight Distributed Ledger Technology",
			publisher: "NIST Computer Security Resource Center",
			url: "https://csrc.nist.gov/projects/privacy-enhancing-lw-distributed-ledger-technology",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "ethereum-contracts",
			label: "Introduction to Smart Contracts & EVM Logic",
			publisher: "Ethereum.org",
			url: "https://ethereum.org/developers/docs/smart-contracts/",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "ethereum-web3",
			label: "Architecture & Principles of Web3",
			publisher: "Ethereum.org",
			url: "https://ethereum.org/web3/",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "wef-future-jobs",
			label: "Future of Jobs Report 2025 – FinTech & Systems Engineering",
			publisher: "World Economic Forum",
			url: "https://www.weforum.org/publications/the-future-of-jobs-report-2025/in-full/2-jobs-outlook/",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "electric-developers",
			label: "Global Crypto Developer Report 2024–2025",
			publisher: "Electric Capital",
			url: "https://www.developerreport.com/developer-report",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "google-ap2",
			label: "Agent Payments Protocol (AP2) and Verifiable Intent",
			publisher: "Google / FIDO Alliance",
			url: "https://blog.google/products-and-platforms/platforms/google-pay/agent-payments-protocol-fido-alliance/",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "coinbase-x402",
			label: "x402 Protocol for Programmatic HTTP Agent Payments",
			publisher: "Coinbase Developer Platform",
			url: "https://docs.cdp.coinbase.com/x402/welcome",
			status: "deployment",
			verifiedAt: "2026-08-21",
		},
		{
			id: "india-nbf",
			label: "Vishvasya National Blockchain Technology Stack Launch",
			publisher: "Ministry of Electronics and Information Technology (MeitY)",
			url: "https://www.pib.gov.in/PressReleseDetailm.aspx?PRID=2051934&lang=2&reg=48",
			status: "production",
			verifiedAt: "2026-08-21",
		},
		{
			id: "india-live-chains",
			label: "National Blockchain Portal Production Dashboard",
			publisher: "NIC Centre of Excellence in Blockchain Technology",
			url: "https://www.blockchain.gov.in/Home/Home",
			status: "production",
			verifiedAt: "2026-08-21",
		},
		{
			id: "india-cbse",
			label: "CBSE Academic Document Chain on National Portal",
			publisher: "NIC Centre of Excellence in Blockchain Technology",
			url: "https://www.blockchain.gov.in/Home/Users?user=CBSC",
			status: "production",
			verifiedAt: "2026-08-21",
		},
		{
			id: "india-property",
			label: "Property Chain Land Records Registry",
			publisher: "NIC Centre of Excellence in Blockchain Technology",
			url: "https://www.blockchain.gov.in/Home/LiveChain?LiveChain=PropertyChain",
			status: "production",
			verifiedAt: "2026-08-21",
		},
		{
			id: "rbi-cbdc",
			label: "Reserve Bank of India CBDC Pilot Updates (Digital Rupee e₹)",
			publisher: "Reserve Bank of India",
			url: "https://www.rbi.org.in/scripts/AnnualReportPublications.aspx?Id=1436",
			status: "pilot",
			verifiedAt: "2026-08-21",
		},
		{
			id: "kinexys",
			label: "Kinexys (formerly Onyx) Institutional Settlement Milestones",
			publisher: "J.P. Morgan Payments",
			url: "https://www.jpmorgan.com/payments/newsroom/kinexys-milestones-2026",
			status: "production",
			verifiedAt: "2026-08-21",
		},
		{
			id: "bis-agora",
			label: "Project Agorá – Wholesale Cross-Border Tokenized Settlement",
			publisher: "Bank for International Settlements (BIS)",
			url: "https://www.bis.org/about/bisih/topics/fmis/agora.htm",
			status: "prototype",
			verifiedAt: "2026-08-21",
		},
		{
			id: "dtcc-tokenization",
			label: "DTCC Digital Assets & Secondary Market Tokenization",
			publisher: "Depository Trust & Clearing Corporation (DTCC)",
			url: "https://www.dtcc.com/digital-assets/tokenization/live-production-trades",
			status: "prelaunch",
			verifiedAt: "2026-08-21",
		},
		{
			id: "walmart-traceability",
			label: "Walmart Food & Pharmaceutical Provenance Deployment",
			publisher: "Walmart Corporate",
			url: "https://corporate.walmart.com/news/2018/09/24/in-wake-of-romaine-e-coli-scare-walmart-deploys-blockchain-to-track-leafy-greens",
			status: "deployment",
			verifiedAt: "2026-08-21",
		},
		{
			id: "tradelens-closure",
			label: "TradeLens Industry Discontinuation & Ecosystem Governance Case",
			publisher: "A.P. Moller–Maersk",
			url: "https://www.maersk.com/news/articles/2022/12/01/information-on-the-closure-of-tradeLens",
			status: "closed",
			verifiedAt: "2026-08-21",
		},
	],
	scenes: [
		// 00-05: THE HOOK & CURIOSITY
		{
			id: "opening",
			kind: "hero",
			section: "hook",
			sectionLabel: "00 · The Keynote Hook",
			durationSeconds: 60,
			eyebrow: "Kristu Jayanti University · Bengaluru · BCA Year 1",
			title: "Blockchain Applications",
			lines: ["FINANCE", "SUPPLY CHAIN", "& BEYOND"],
			callout: "Manoj Mukherjee · Founder · AI Scientist · Enterprise AI Architect",
			image: {
				src: "/images/lectures/blockchain-ai-network.webp",
				alt: "Distributed interconnected cryptographic nodes with an AI agent intelligence layer",
				preload: true,
			},
			notes: notes(
				"Good afternoon BCA 1st Year. We are not starting today with boring slide definitions or crypto trading buzzwords. Today, we are going to look at blockchain the way an enterprise software founder looks at systems: we will build a chain in the browser, attack it live, break it, fix it, and discover why the world's largest banks, governments, and AI systems care about this architecture.",
				"Open the fundamental question about human and digital trust.",
			),
		},
		{
			id: "hook-who-do-you-trust",
			kind: "statement",
			section: "hook",
			sectionLabel: "01 · The Trust Question",
			durationSeconds: 90,
			eyebrow: "The Core Problem of Digital Trust",
			title: "WHO DO YOU TRUST?",
			statement: "If Manoj sends ₹10,000 to Rahul... how do we BOTH prove the transaction happened without relying on a single fallible party?",
			fragments: ["Payer", "Payee", "Bank Database", "Intermediaries", "Shared Truth"],
			notes: notes(
				"Ask the room: 'If I transfer ₹10,000 to Rahul right now on UPI, what actually happened?' Students will say 'the money moved.' But physically, nothing moved. Two private database records were updated by a central bank server. What happens when multiple independent companies or countries need to agree on truth without trusting a single central server?",
				"Let's see what happens when five independent organizations try to coordinate with their own separate databases.",
				"Who has the ultimate power to reverse or rewrite a normal database?",
				"The database administrator or central server owner.",
			),
		},
		{
			id: "trust-problem-silos",
			kind: "demo",
			demoId: "trust-problem",
			section: "hook",
			sectionLabel: "02 · The Database Silo Problem",
			durationSeconds: 150,
			title: "FIVE COMPANIES. FIVE DATABASES.",
			callout: "Manufacturer → Distributor → Warehouse → Retailer → Clinic. Who has the single source of truth?",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Click 'Simulate Silo Conflict'. Notice how Distributor logged 85 units while Warehouse logged 100 units. Neither party can prove who is right because both are looking at their own private SQL databases. Now click 'Switch to Shared Ledger'. When every custody event is cryptographically signed and replicated, consensus enforces a single shared truth.",
				"Now let's contrast when you need a database versus when you need a blockchain.",
			),
		},
		{
			id: "database-or-blockchain",
			kind: "comparison",
			section: "hook",
			sectionLabel: "03 · Architectural Contrast",
			durationSeconds: 105,
			title: "Database vs. Blockchain",
			left: {
				label: "Single Organization (Database)",
				steps: ["College ERP", "PostgreSQL", "Student Query"],
				caption: "Fast, cheap, and private. 100% appropriate when one trusted organization owns and governs the entire system.",
			},
			right: {
				label: "Multi-Party Consortium (Blockchain)",
				steps: ["College", "Employer", "University", "Shared Cryptographic Proof"],
				caption: "Tamper-evident and verifiable when independently governed parties need common history without a single administrator.",
			},
			sourceIds: ["nist-fit"],
			notes: notes(
				"Rule of thumb for your BCA engineering career: If only one company owns the data, USE A DATABASE. Blockchain introduces consensus and synchronization overhead—you only earn that complexity when multiple independently governed parties need to share state without trusting each other.",
				"Let's summarize blockchain in one precise sentence.",
			),
		},

		// 10-15: FOUNDATIONS & THE ATOMIC PIECES
		{
			id: "one-sentence",
			kind: "statement",
			section: "foundations",
			sectionLabel: "04 · Foundations",
			durationSeconds: 75,
			eyebrow: "Blockchain in One Engineering Sentence",
			title: "A SHARED, TAMPER-EVIDENT LEDGER",
			statement: "Maintained by multiple independently governed participants.",
			fragments: ["Shared State", "Tamper-Evident", "Cryptographic Link", "Consensus Rules"],
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Notice what is NOT in this sentence: Bitcoin, mining, tokens, or speculation. Blockchain is a distributed coordination architecture. 'Shared' means replicated history. 'Tamper-evident' means any unauthorized modification is mathematically exposed.",
				"Let's trace what happens when you click SEND.",
			),
		},
		{
			id: "transaction-journey",
			kind: "flow",
			section: "foundations",
			sectionLabel: "05 · Data Flow",
			durationSeconds: 120,
			title: "What happens after you click SEND?",
			steps: ["Transaction Proposal", "Peer Broadcast", "Cryptographic Validation", "Block Packaging", "Hash Linking", "Consensus Commit"],
			callout: "A block is committed, agreed history—not merely a temporary database cache.",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Walk through the pipeline: 1) Client creates a payload. 2) Broadcasts to the network. 3) Nodes check signatures and rules. 4) Packaged into a block. 5) Cryptographically linked to the previous block. 6) Committed to all ledgers.",
				"Let's look at the foundational cryptographic primitive that makes this possible: the SHA-256 Hash.",
			),
		},
		{
			id: "hash-avalanche-demo",
			kind: "demo",
			demoId: "hash",
			section: "foundations",
			sectionLabel: "06 · Cryptography Lab",
			durationSeconds: 150,
			title: "ONE CHARACTER CHANGES EVERYTHING",
			callout: "Live Web Crypto SHA-256 Hashing · 32-Byte Avalanche Shift",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"This is real SHA-256 running right now in this browser using the Web Crypto API. Click '₹10,001 (1 Digit Change)'. Watch the 32-byte heatmap instantly shift from green to red. Changing one single digit does not change 1% of the hash—it completely transforms the entire 256-bit fingerprint. This is the Avalanche Effect.",
				"Now let's see how this hash connects one block to the next.",
			),
		},
		{
			id: "block-anatomy",
			kind: "diagram",
			diagramId: "block-anatomy",
			section: "foundations",
			sectionLabel: "07 · Block Anatomy",
			durationSeconds: 90,
			title: "Inside One Block",
			callout: "TRANSACTION DATA + PREVIOUS HASH + CALCULATED HASH",
			notes: notes(
				"Click each field in Block #2. Notice that Block #2 stores two crucial fingerprints: 1) Its own calculated hash. 2) The Previous Hash pointing to Block #1. This previous-hash pointer is the digital glue that creates the chain.",
				"Let's see what happens when multiple blocks are linked together.",
			),
		},
		{
			id: "chain-links",
			kind: "diagram",
			diagramId: "chain-links",
			section: "foundations",
			sectionLabel: "08 · The Chain",
			durationSeconds: 90,
			title: "Every Block Remembers The One Before",
			callout: "Change Block #1 → Block #2 still points to the old fingerprint",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Click 'Tamper Block #1'. Because Block #1's data changed, its real fingerprint changed. But Block #2's previous-hash pointer is still looking for the old fingerprint. The link is severed.",
				"How do independent computers across the world agree on which blocks are valid?",
			),
		},
		{
			id: "consensus-network",
			kind: "demo",
			demoId: "consensus-flow",
			section: "foundations",
			sectionLabel: "09 · Consensus Lab",
			durationSeconds: 180,
			title: "HOW DOES A NETWORK AGREE?",
			callout: "Interactive 5-Node Consensus · Propose → Validate → Agree → Commit",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Here are 5 validator nodes across Bengaluru, Mumbai, Delhi, Hyderabad, and Chennai running in React Flow. Click 'Advance Consensus Step'. Step 1 broadcasts the candidate block. Step 2 validates the rules. Step 3 reaches supermajority agreement. Step 4 commits the block simultaneously to all 5 node ledgers.",
				"Now let's make a critical industry distinction that every student must understand.",
			),
		},
		{
			id: "blockchain-not-crypto",
			kind: "diagram",
			diagramId: "branching-tree",
			section: "foundations",
			sectionLabel: "10 · Major Visual Statement",
			durationSeconds: 105,
			eyebrow: "Enterprise Clarification",
			title: "BLOCKCHAIN ≠ CRYPTOCURRENCY",
			callout: "Blockchain is the distributed operating engine; Cryptocurrency was merely its first financial experiment.",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Repeat this to your professors and interviewers: Blockchain is the underlying coordination architecture; crypto is just one volatile consumer application built on top of it. Enterprise blockchain powers global trade finance, vaccine supply chains, and government digital identity.",
				"Let's examine how the Web evolved to this point.",
			),
		},
		{
			id: "web-evolution",
			kind: "demo",
			demoId: "web-evolution",
			section: "foundations",
			sectionLabel: "11 · Web Architecture",
			durationSeconds: 120,
			title: "THE EVOLUTION OF THE WEB",
			callout: "Web 1: Read · Web 2: Read + Write · Web 3: Read + Write + Own / Verify",
			sourceIds: ["ethereum-web3"],
			notes: notes(
				"Click between Web 1, Web 2, and Web 3. Web 1: Static HTML pages owned by server hosts. Web 2: User-generated content stored inside centralized databases (Google, Meta, AWS). Web 3: Users and open protocols hold verifiable cryptographic identity and state.",
				"Let's see how cryptographic identity works with digital signatures.",
			),
		},
		{
			id: "digital-signature",
			kind: "demo",
			demoId: "signature",
			section: "demo",
			sectionLabel: "12 · Signature Lab",
			durationSeconds: 120,
			title: "SIGN IT. THEN TRY TO FAKE IT.",
			callout: "Browser ECDSA P-256 Keypair · Private Key Signs · Public Key Verifies",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"A hash proves data was not corrupted; a digital signature proves WHO authorized it. Click 'Create key + sign'. Now change '001' to '002' in the message and click 'Verify current message'. The signature instantly fails. The private key never leaves the signer.",
				"Now, let's combine hashes, links, and signatures for our centerpiece live attack.",
			),
		},

		// 15-30: THE WOW MOMENT – LIVE TAMPER ATTACK
		{
			id: "tamper-prediction",
			kind: "question",
			section: "demo",
			sectionLabel: "13 · Interactive Prediction",
			title: "Prediction: Attack on Block #2",
			durationSeconds: 60,
			question: "What happens if an attacker secretly edits Block #2 from 100 boxes to 1,000 boxes in a live chain?",
			options: [
				"Only Block #2 fails",
				"Block #2 fails AND downstream trust collapses",
				"The network automatically accepts the change",
			],
			correctIndex: 1,
			explanation: "Block #2's calculated hash immediately mismatches its stored hash, and Block #3's previous pointer points to an invalid fingerprint. Downstream verification collapses.",
			stats: [12, 82, 6],
			notes: notes(
				"Ask the students to commit to an answer. Let's see the vote distribution.",
				"Now, let's run the attack live in the integrity lab.",
			),
		},
		{
			id: "integrity-lab-wow",
			kind: "demo",
			demoId: "integrity",
			section: "demo",
			sectionLabel: "14 · Live Integrity Lab",
			durationSeconds: 180,
			title: "⚡ LIVE BLOCKCHAIN TAMPER ATTACK",
			callout: "Click TAMPER to break the chain · Click RESTORE to repair cryptographic trust",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Click '⚡ TAMPER WITH BLOCK #2'. Look at the screen: Block #2 turns bright red with 'INTEGRITY FAILED: Stored Hash ≠ Calculated Hash'. Block #3's link turns red because its pointer is broken. Downstream trust is shattered. Now click 'RESTORE / REPAIR CHAIN'. All blocks turn green: 'CHAIN INTEGRITY VERIFIED ✓'. Tamper-evident does not mean impossible to edit—it means an edit is mathematically impossible to hide.",
				"Now let's add programmable business rules to that shared chain.",
			),
		},
		{
			id: "smart-contract-demo",
			kind: "demo",
			demoId: "smart-contract",
			section: "demo",
			sectionLabel: "15 · Smart Contracts",
			durationSeconds: 150,
			title: "RULES BECOME EXECUTABLE CODE",
			callout: "IF Received ✓ AND Quality Check ✓ AND Temp < 8°C ✓ → Release ₹5,00,000",
			sourceIds: ["ethereum-contracts"],
			notes: notes(
				"A smart contract is deterministic code deployed on a distributed ledger. Notice the conditions: 1) Medicine received. 2) Lab test passed. 3) Temp kept below 8°C. 4) Not expired. Toggle off 'Temp Maintained'. The contract instantly evaluates: 'PAYMENT BLOCKED'. Turn it back on: '₹5,00,000 RELEASED'. No human clerk needed; code executed agreed terms.",
				"Let's see how smart contracts fit inside real enterprise software architecture.",
			),
		},
		{
			id: "enterprise-architecture",
			kind: "demo",
			demoId: "enterprise-arch-flow",
			section: "demo",
			sectionLabel: "16 · Systems Architecture",
			durationSeconds: 150,
			title: "BLOCKCHAIN IS A COMPONENT",
			callout: "Next.js UI → FastAPI Gateway → ERP / SQL Database + Blockchain Settlement",
			notes: notes(
				"Look at this enterprise architecture in React Flow. 90% of an enterprise application is normal cloud software: Next.js frontend, authentication, FastAPI gateways, PostgreSQL databases, SAP ERPs. Blockchain is just the specialized multi-party consensus and settlement rail on the right. Never build an entire app on blockchain—use it as a component.",
				"So when should an engineer actually use blockchain?",
			),
		},
		{
			id: "decision-tree",
			kind: "demo",
			demoId: "decision-tree",
			section: "demo",
			sectionLabel: "17 · Engineering Judgment",
			durationSeconds: 150,
			title: "WHEN NOT TO USE BLOCKCHAIN",
			callout: "Interactive 4-Step Architecture Diagnostic: Blockchain vs. Database",
			sourceIds: ["nist-fit"],
			notes: notes(
				"Walk through the 4 questions with the class: 1) Multiple independent orgs? 2) Need shared read/write? 3) Limited mutual trust? 4) Tamper-evident audit required? If any answer is NO, the tool tells you: 'USE A NORMAL DATABASE (PostgreSQL)'. This is real engineering judgment.",
				"Now let's examine blockchain in Finance and Banking.",
			),
		},

		// 30-45: FINANCE & SUPPLY CHAIN INDUSTRY PRODUCTION
		{
			id: "finance-intro",
			kind: "hero",
			section: "finance",
			sectionLabel: "18 · Finance Rails",
			durationSeconds: 60,
			eyebrow: "Industry Vertical 01 · Global Banking",
			title: "FINANCE MOVES VALUE",
			lines: ["PAYMENTS", "SETTLEMENT", "TOKENIZATION"],
			callout: "Moving money across borders is slow because every bank maintains a private ledger that must be manually reconciled.",
			image: {
				src: "/images/lectures/institutional-settlement.webp",
				alt: "Institutional banking core connected via shared programmable settlement rails",
			},
			notes: notes(
				"Finance is the biggest enterprise user of blockchain. Why? Because moving $100 million between London and Mumbai today takes 2 to 3 days and passes through 6 intermediary correspondent banks. Let's see the comparison.",
				"Look at traditional multi-hop settlement versus atomic shared rails.",
			),
		},
		{
			id: "settlement-compare",
			kind: "diagram",
			diagramId: "settlement-flow",
			section: "finance",
			sectionLabel: "19 · Settlement Rails",
			durationSeconds: 120,
			title: "Traditional vs. Programmable Settlement",
			callout: "Left: 7 Steps & 3 Days · Right: Atomic Real-Time Settlement",
			notes: notes(
				"Left side: Bank A → Correspondent Bank 1 → SWIFT → Correspondent Bank 2 → Bank B. Each bank maintains a separate ledger that requires batch reconciliation. Right side: Both banks participate on a shared programmable settlement rail. Money and assets swap atomically in seconds.",
				"Let's look at the real-world bank doing this in production right now.",
			),
		},
		{
			id: "kinexys-case",
			kind: "sources",
			section: "finance",
			sectionLabel: "20 · Production Case Study",
			durationSeconds: 90,
			eyebrow: "Production Institutional Rail · J.P. Morgan",
			title: "J.P. Morgan Kinexys",
			items: [
				{
					title: "$3 Trillion+ Total Volume Processed",
					detail: "Over $5 Billion average daily volume moving institutional money 24/7 across global banking participants.",
					status: "production",
					sourceId: "kinexys",
				},
				{
					title: "Project Agorá (BIS + 7 Central Banks)",
					detail: "Testing tokenized commercial bank deposits and wholesale central bank reserves for cross-border atomic settlement.",
					status: "prototype",
					sourceId: "bis-agora",
				},
			],
			notes: notes(
				"J.P. Morgan's Kinexys (formerly Onyx) is not a crypto coin. It is a permissioned blockchain where global corporations and banks settle trillions of dollars in real institutional funds 24/7. That is production engineering.",
				"What about India's central bank digital currency?",
			),
		},
		{
			id: "digital-rupee",
			kind: "sources",
			section: "finance",
			sectionLabel: "21 · Digital Rupee Pilot",
			durationSeconds: 90,
			eyebrow: "Reserve Bank of India (RBI)",
			title: "e₹ · Digital Rupee",
			items: [
				{
					title: "Retail (e₹-R) & Wholesale (e₹-W) Pilots",
					detail: "RBI is piloting programmable digital cash, offline transaction capability, and interbank settlement.",
					status: "pilot",
					sourceId: "rbi-cbdc",
				},
				{
					title: "DTCC Digital Assets Tokenization",
					detail: "Depository Trust & Clearing Corp executing live production trades for tokenized securities.",
					status: "prelaunch",
					sourceId: "dtcc-tokenization",
				},
			],
			notes: notes(
				"Notice the official label from RBI: Pilot. As software engineers, always distinguish between Production, Pilot, Prototype, and Prelaunch. Do not oversell a pilot as completed production.",
				"Let's review the 2026 industry maturity matrix.",
			),
		},
		{
			id: "finance-maturity",
			kind: "demo",
			demoId: "industry-reality",
			section: "finance",
			sectionLabel: "22 · Industry Reality Matrix",
			durationSeconds: 120,
			title: "WHAT IS ACTUALLY LIVE IN 2026?",
			callout: "Production ≠ Pilot ≠ Prototype ≠ Prelaunch ≠ Closed",
			sourceIds: ["kinexys", "rbi-cbdc", "bis-agora", "dtcc-tokenization", "india-live-chains", "india-nbf", "walmart-traceability", "tradelens-closure"],
			notes: notes(
				"Click across Finance, India, Supply Chain, and AI Agents. This matrix teaches students how to evaluate technology claims objectively.",
				"Now let's move to our second major vertical: Supply Chain & Medicine Logistics.",
			),
		},
		{
			id: "medicine-journey",
			kind: "demo",
			demoId: "supply-chain",
			section: "supply-chain",
			sectionLabel: "23 · Supply Chain Lab",
			durationSeconds: 150,
			title: "FOLLOW BATCH PCM-001",
			callout: "Manufacturer → Distributor → Warehouse → Hospital → Patient",
			notes: notes(
				"Click through the 5 stages of Paracetamol Batch PCM-001. Now click 'Tamper distributor quantity'. The quantity becomes 1,000, and the cryptographic verification badge immediately switches from Verified to Integrity Failed. We can trace backwards from the patient to the original factory lot number.",
				"Let's look at India's live government deployment in medicine logistics.",
			),
		},
		{
			id: "india-drug-logistics",
			kind: "sources",
			section: "supply-chain",
			sectionLabel: "24 · Live Indian Deployment",
			durationSeconds: 75,
			eyebrow: "National Blockchain Portal · NIC",
			title: "Drug Logistics Chain",
			items: [
				{
					title: "Central Procurement → State Warehouse → Hospital",
					detail: "NIC lists Drug Logistics among its live operational chains for counterfeit prevention and stock provenance.",
					status: "production",
					sourceId: "india-live-chains",
				},
			],
			notes: notes(
				"India's National Informatics Centre (NIC) operates live permissioned blockchain nodes across government data centres to verify critical medical supplies.",
				"Let's also learn from a major corporate failure: TradeLens.",
			),
		},
		{
			id: "supply-chain-lessons",
			kind: "sources",
			section: "supply-chain",
			sectionLabel: "25 · Enterprise Case Study",
			durationSeconds: 90,
			title: "Technology Works · Governance Fails",
			items: [
				{
					title: "Walmart Leafy Greens Traceability",
					detail: "Reduced tracking time for contaminated produce from 7 days down to 2.2 seconds.",
					status: "deployment",
					sourceId: "walmart-traceability",
				},
				{
					title: "TradeLens (IBM + Maersk) Discontinued",
					detail: "Technically viable, but competitors refused to join a platform controlled primarily by Maersk. Shut down in 2022.",
					status: "closed",
					sourceId: "tradelens-closure",
				},
			],
			notes: notes(
				"TradeLens is a classic case study: IBM and Maersk built great code, but other shipping lines refused to join because they didn't trust Maersk's governance. A blockchain ecosystem succeeds on neutral governance and economic incentives—not just software.",
				"Let's look at India's national infrastructure stack: Vishvasya.",
			),
		},

		// 45-55: BEYOND & AI CONVERGENCE
		{
			id: "vishvasya-india",
			kind: "sources",
			section: "beyond",
			sectionLabel: "26 · National Infrastructure",
			durationSeconds: 75,
			eyebrow: "MeitY Government Infrastructure · India",
			title: "VISHVASYA",
			items: [
				{
					title: "National Blockchain Framework (BaaS)",
					detail: "Launched in September 2024 by MeitY across NIC data centres in Delhi, Hyderabad, and Bhubaneswar.",
					status: "production",
					sourceId: "india-nbf",
				},
			],
			notes: notes(
				"Vishvasya is India's Blockchain-as-a-Service stack, allowing state and central government departments to deploy tamper-evident citizen registries.",
				"Let's see one live citizen use case every student in this room has touched: CBSE certificates.",
			),
		},
		{
			id: "cbse-credentials",
			kind: "sources",
			section: "beyond",
			sectionLabel: "27 · Education Credentials",
			durationSeconds: 75,
			eyebrow: "Academic Document Chain · CBSE",
			title: "Verify The Credential, Not A Photocopy",
			items: [
				{
					title: "CBSE Academic Records on-Chain",
					detail: "Academic document hashes for Class 10 & 12 are stored on-chain, allowing employers and universities to instantly verify authenticity.",
					status: "production",
					sourceId: "india-cbse",
				},
			],
			notes: notes(
				"When an employer checks your degree, they shouldn't need a stamped photocopy. They verify the digital signature of the university on the blockchain ledger.",
				"Let's explore the multi-industry ecosystem wheel.",
			),
		},
		{
			id: "beyond-ecosystem-radial",
			kind: "demo",
			demoId: "ecosystem-radial",
			section: "beyond",
			sectionLabel: "28 · Multi-Industry Radial",
			durationSeconds: 150,
			title: "THE MULTI-INDUSTRY ECOSYSTEM",
			callout: "Interactive Explorer: 8 Enterprise Sectors Beyond Cryptocurrency",
			notes: notes(
				"Click across Healthcare, Education, Real Estate, Agriculture, Climate, and AI IP. Every branch has a concrete, verified engineering problem and solution.",
				"Now let's look at the future: the intersection of AI Agents and Blockchain.",
			),
		},
		{
			id: "ai-blockchain-convergence",
			kind: "demo",
			demoId: "ai-convergence",
			section: "beyond",
			sectionLabel: "29 · AI × Blockchain",
			durationSeconds: 180,
			title: "AI ACTS. BLOCKCHAIN PROVES.",
			callout: "AI Can Reason · Blockchain Can Verify · Smart Contracts Can Execute · Cloud Can Scale",
			sourceIds: ["google-ap2", "coinbase-x402"],
			notes: notes(
				"AI models (LLMs and agents) are probabilistic: they reason, plan, and propose actions. But when an AI agent needs to book a server, hire a sub-agent, or pay an API, it needs a deterministic rail with strict spending limits and cryptographic receipts. Google recently open-sourced AP2 with FIDO, and Coinbase launched x402 for HTTP agent payments. AI provides the intelligence; Blockchain provides the verifiable ledger.",
				"Let's test what we've learned with a final architecture question.",
			),
		},
		{
			id: "quiz-crypto-vs-blockchain",
			kind: "question",
			section: "beyond",
			sectionLabel: "30 · Final Architecture Poll",
			title: "Architecture Poll: Where Does Blockchain Fit?",
			durationSeconds: 60,
			question: "Which of the following problems MOST genuinely justifies building on a blockchain?",
			options: [
				"A university canteen lunch pre-order app",
				"Cross-border pharmaceutical anti-counterfeit traceability across 4 countries",
				"A high-speed real-time multiplayer 3D video game",
			],
			correctIndex: 1,
			explanation: "Cross-border pharmaceutical tracking involves multiple sovereign jurisdictions, independent companies, limited mutual trust, and high audit requirements. Canteen apps and video games are far better served by centralized cloud databases.",
			stats: [4, 91, 5],
			notes: notes(
				"91% of students got this right! That is real engineering discernment.",
				"Let's discuss why this skill commands a premium in software engineering.",
			),
		},

		// 55-60: CAREER ROADMAP & INSPIRATIONAL CLOSING
		{
			id: "why-premium-engineers",
			kind: "cards",
			section: "career",
			sectionLabel: "31 · Career Value",
			durationSeconds: 120,
			title: "WHY DOES THIS SKILL COMMAND A PREMIUM?",
			items: [
				{ title: "Rare Intersection", detail: "Distributed systems + cryptography + security + enterprise finance." },
				{ title: "High Financial Stakes", detail: "A tiny smart contract bug can expose millions in real funds. Precision engineering is mandatory." },
				{ title: "Irreversible State", detail: "Deployed ledger protocols cannot simply be hot-patched on production without governance." },
				{ title: "AI-Era Agents", detail: "Autonomous agents will require secure wallets, verifiable identity, and programmatic micro-settlements." },
				{ title: "Production Ownership", detail: "Consensus nodes, key management, telemetry, and distributed incident response." },
				{ title: "Business Translation", detail: "Engineers who can clearly explain governance, regulation, and architecture tradeoffs." },
			],
			callout: "Premium compensation follows scarce engineering judgment—not merely writing Solidity syntax.",
			sourceIds: ["wef-future-jobs", "electric-developers"],
			notes: notes(
				"Don't chase buzzwords. The engineers who build high-value careers are those who master distributed systems, networks, cryptography, and real-world trade-offs.",
				"Here is your concrete roadmap starting from BCA Year 1.",
			),
		},
		{
			id: "career-roadmap",
			kind: "cards",
			section: "career",
			sectionLabel: "32 · Student Roadmap",
			durationSeconds: 150,
			eyebrow: "BCA Year 1 · Master in this sequence",
			title: "YOUR SYSTEMS ROADMAP STARTS TODAY",
			items: [
				{ title: "01 · Programming & Data Structures", detail: "TypeScript or Python, Git, memory structures, algorithms, and linked lists." },
				{ title: "02 · Systems & Networks", detail: "HTTP, TCP/IP, client-server models, REST APIs, Linux, and PostgreSQL." },
				{ title: "03 · Applied Cryptography", detail: "SHA-256 hashes, symmetric AES, asymmetric RSA/ECDSA, and public-key infrastructure." },
				{ title: "04 · Blockchain Foundations", detail: "Build a local blockchain in 100 lines of TypeScript; understand consensus and state." },
				{ title: "05 · Smart Contracts & EVM", detail: "Write deterministic business logic; test edge-cases, vulnerabilities, and unit tests." },
				{ title: "06 · AI & Agent Orchestration", detail: "Connect LLM reasoning agents to verifiable API tools and scoped payment wallets." },
			],
			callout: "First Year Portfolio: Build this lecture's hash-linked chain locally in TypeScript.",
			notes: notes(
				"Do not start by buying crypto. Start by writing TypeScript, building a linked-list hash chain locally, and connecting a small AI agent that can propose actions to a human verifier.",
				"Let's review the 4 fundamental truths.",
			),
		},
		{
			id: "four-truths",
			kind: "cards",
			section: "closing",
			sectionLabel: "33 · Summary",
			durationSeconds: 75,
			title: "FOUR TRUTHS TO REMEMBER",
			items: [
				{ title: "1. Shared Replicated History", detail: "Multiple parties coordinate around a single tamper-evident state." },
				{ title: "2. Cryptographic Hashes", detail: "One small change completely alters the fingerprint and breaks downstream links." },
				{ title: "3. Consensus Rules", detail: "Independent nodes agree on valid state without relying on one single administrator." },
				{ title: "4. Architecture Fit First", detail: "If one trusted company owns the data, a normal database is 10,000x better." },
			],
			sourceIds: ["nist-blockchain", "nist-fit"],
			notes: notes(
				"Shared history. Tamper-evident hashes. Consensus rules. Architecture fit. Remember these four principles.",
				"Let's close with our final challenge and the live student takeaway.",
			),
		},
		{
			id: "final-challenge-qr",
			kind: "demo",
			demoId: "qr-takeaway",
			section: "closing",
			sectionLabel: "34 · Student Takeaway & Challenge",
			durationSeconds: 150,
			title: "THE NEXT TECHNOLOGY YOU BUILD",
			callout: "If you could solve ONE real-world trust problem with software... what will you build?",
			notes: notes(
				"Scan the QR code on screen. The entire interactive lecture studio runs live in your mobile browser. Go home, run the tamper attacks, break the chain, and start building. Technology changes every decade—but your engineering fundamentals compound forever. Thank you Kristu Jayanti University!",
				"Open the floor for questions from BCA Year 1 students.",
			),
		},
	],
};
