import type { Lecture } from "@/lib/lectures/types";

const notes = (
	say: string,
	transition: string,
	ask?: string,
	expected?: string,
) => ({ say, transition, ask, expected });

export const blockchainLecture: Lecture = {
	slug: "blockchain-finance-supply-chain",
	shortTitle: "Blockchain: Finance, Supply Chain & Beyond",
	title: "Blockchain Applications in Finance, Supply Chain & Beyond",
	description:
		"A research-backed 60-minute interactive lecture that builds blockchain from first principles, tests it in the browser, examines documented industry systems, and frames a responsible 2030 outlook.",
	audience: "BCA 1st Year · Kristu Jayanti University, Bengaluru",
	presenter: "Manoj Mukherjee · Founder & AI Scientist @ NammaGuide · Enterprise AI Architect",
	totalMinutes: 60,
	sources: [
		{
			id: "nist-blockchain",
			label: "Blockchain Architecture and Security Overview",
			publisher: "US National Institute of Standards and Technology (NIST)",
			url: "https://www.nist.gov/blockchain",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "nist-fit",
			label: "Privacy-Enhancing Lightweight Distributed Ledger Technology",
			publisher: "NIST Computer Security Resource Center",
			url: "https://csrc.nist.gov/projects/privacy-enhancing-lw-distributed-ledger-technology",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "ethereum-contracts",
			label: "Introduction to Smart Contracts & EVM Logic",
			publisher: "Ethereum.org",
			url: "https://ethereum.org/developers/docs/smart-contracts/",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "ethereum-web3",
			label: "Architecture & Principles of Web3",
			publisher: "Ethereum.org",
			url: "https://ethereum.org/web3/",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "wef-future-jobs",
			label: "Future of Jobs Report 2025 – FinTech & Systems Engineering",
			publisher: "World Economic Forum",
			url: "https://www.weforum.org/publications/the-future-of-jobs-report-2025/in-full/2-jobs-outlook/",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "google-ap2",
			label: "Agent Payments Protocol (AP2) and Verifiable Intent",
			publisher: "Google / FIDO Alliance",
			url: "https://blog.google/products-and-platforms/platforms/google-pay/agent-payments-protocol-fido-alliance/",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "coinbase-x402",
			label: "x402 Protocol for Programmatic HTTP Agent Payments",
			publisher: "Coinbase Developer Platform",
			url: "https://docs.cdp.coinbase.com/x402/welcome",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "w3c-vc-2",
			label: "Verifiable Credentials 2.0 Recommendation",
			publisher: "World Wide Web Consortium (W3C)",
			url: "https://www.w3.org/news/2025/the-verifiable-credentials-2-0-family-of-specifications-is-now-a-w3c-recommendation/",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "bis-tokenisation-vision",
			label: "Next-Generation Monetary and Financial System",
			publisher: "Bank for International Settlements (BIS)",
			url: "https://www.bis.org/publ/arpdf/ar2025e3.htm",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "fsb-cross-border-targets",
			label: "G20 Targets for Enhancing Cross-Border Payments",
			publisher: "Financial Stability Board (FSB)",
			url: "https://www.fsb.org/work-of-the-fsb/financial-innovation-and-structural-change/cross-border-payments/g20-targets-for-enhancing-cross-border-payments-2/",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "india-nbf",
			label: "Vishvasya National Blockchain Technology Stack Launch",
			publisher: "Ministry of Electronics and Information Technology (MeitY)",
			url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2051934&lang=1&reg=3",
			status: "production",
			verifiedAt: "2026-08-21",
		},
		{
			id: "india-live-chains",
			label: "National Blockchain Portal Production Dashboard",
			publisher: "NIC Centre of Excellence in Blockchain Technology",
			url: "https://www.blockchain.gov.in/Home/Home",
			status: "production",
			verifiedAt: "2026-08-21",
		},
		{
			id: "india-cbse",
			label: "CBSE Academic Document Chain on National Portal",
			publisher: "NIC Centre of Excellence in Blockchain Technology",
			url: "https://www.blockchain.gov.in/Home/LiveChain?LiveChain=CertChain",
			status: "production",
			verifiedAt: "2026-08-21",
		},
		{
			id: "india-drug-logistics",
			label: "Drug Logistics Chain",
			publisher: "NIC Centre of Excellence in Blockchain Technology",
			url: "https://www.blockchain.gov.in/Home/LiveChain?LiveChain=LogisticsChain",
			status: "production",
			verifiedAt: "2026-08-21",
		},
		{
			id: "india-property",
			label: "Property Chain Land Records Registry",
			publisher: "NIC Centre of Excellence in Blockchain Technology",
			url: "https://www.blockchain.gov.in/Home/LiveChain?LiveChain=PropertyChain",
			status: "production",
			verifiedAt: "2026-08-21",
		},
		{
			id: "rbi-cbdc",
			label: "Reserve Bank of India CBDC Pilot Updates (Digital Rupee e₹)",
			publisher: "Reserve Bank of India",
			url: "https://www.rbi.org.in/scripts/AnnualReportPublications.aspx?Id=1436",
			status: "pilot",
			verifiedAt: "2026-08-21",
		},
		{
			id: "kinexys",
			label: "Kinexys (formerly Onyx) Institutional Settlement Milestones",
			publisher: "J.P. Morgan Payments",
			url: "https://www.jpmorgan.com/payments/newsroom/kinexys-milestones-2026",
			status: "production",
			verifiedAt: "2026-08-21",
		},
		{
			id: "bis-agora",
			label: "Project Agorá – Wholesale Cross-Border Tokenized Settlement",
			publisher: "Bank for International Settlements (BIS)",
			url: "https://www.bis.org/about/bisih/topics/fmis/agora.htm",
			status: "prototype",
			verifiedAt: "2026-08-21",
		},
		{
			id: "dtcc-tokenization",
			label: "DTCC Digital Assets & Secondary Market Tokenization",
			publisher: "Depository Trust & Clearing Corporation (DTCC)",
			url: "https://www.dtcc.com/digital-assets/tokenization/live-production-trades",
			status: "prelaunch",
			verifiedAt: "2026-08-21",
		},
		{
			id: "walmart-traceability",
			label: "Walmart Leafy-Greens Traceability Deployment (2018)",
			publisher: "Walmart Corporate",
			url: "https://corporate.walmart.com/news/2018/09/24/in-wake-of-romaine-e-coli-scare-walmart-deploys-blockchain-to-track-leafy-greens",
			status: "deployment",
			verifiedAt: "2026-08-21",
		},
		{
			id: "tradelens-closure",
			label: "TradeLens Industry Discontinuation & Ecosystem Governance Case",
			publisher: "A.P. Moller–Maersk",
			url: "https://www.maersk.com/news/articles/2022/12/01/information-on-the-closure-of-tradeLens",
			status: "closed",
			verifiedAt: "2026-08-21",
		},
	],
	scenes: [
		// 00-05: THE HOOK & CURIOSITY
		{
			id: "opening",
			kind: "hero",
			variant: "founder",
			section: "hook",
			sectionLabel: "00 · Opening",
			durationSeconds: 60,
			eyebrow: "Founder Keynote · Bengaluru · 2026",
			title: "Blockchain applications in finance, supply chain and beyond",
			headlineLines: [
				"Blockchain applications",
				"in finance, supply chain",
				"and beyond",
			],
			speaker: {
				name: "Manoj Mukherjee",
				role: "Founder & AI Scientist @ NammaGuide",
				summary: "Enterprise AI Architect · 10+ years building production AI and digital platforms.",
			},
			notes: notes(
				"Good afternoon. I am Manoj Mukherjee, Founder and AI Scientist at NammaGuide, and an Enterprise AI Architect. For more than ten years, I have worked across enterprise platforms, cloud-native systems, and production AI. Today I want to bring that systems perspective to blockchain. We will build a small chain in this browser, break it, inspect why it failed, and use real industry evidence to decide where this architecture belongs—and where it does not.",
				"Begin with a familiar payment and ask what digital trust actually requires.",
			),
		},
		{
			id: "hook-who-do-you-trust",
			kind: "statement",
			section: "hook",
			sectionLabel: "01 · The Trust Question",
			durationSeconds: 90,
			eyebrow: "The Core Problem of Digital Trust",
			title: "WHO DO YOU TRUST?",
			statement: "If Manoj sends ₹10,000 to Rahul, what record lets both parties verify what happened—and who is allowed to change it?",
			fragments: ["Payer", "Payee", "Bank Database", "Intermediaries", "Accepted Record"],
			notes: notes(
				"Ask the room: 'If I transfer ₹10,000 on UPI, what actually changed?' The payment is authorized and recorded through participating banks and the NPCI-operated network; it is not a coin travelling through a phone. Central coordination works well here. The blockchain question begins only when several independently governed parties need a common history and no participant should own the master record.",
				"Let's see what happens when five independent organizations try to coordinate with their own separate databases.",
				"Who has the ultimate power to reverse or rewrite a normal database?",
				"The database administrator or central server owner.",
			),
		},
		{
			id: "trust-problem-silos",
			kind: "demo",
			demoId: "trust-problem",
			section: "hook",
			sectionLabel: "02 · The Database Silo Problem",
			durationSeconds: 150,
			title: "FIVE COMPANIES. FIVE DATABASES.",
			callout: "Example manufacturer → distributor → warehouse → retailer → clinic. Which records do the parties accept?",
			image: {
				src: "/images/lectures/trust-silo-infographic.webp",
				alt: "Fragmented Corporate Database Silos vs Unified Cryptographic Blockchain Ledger",
			},
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Click 'Simulate Silo Conflict'. One example record says 85 units; another says 100. The disagreement is real, but a ledger cannot discover which physical count is true by itself. Click 'Switch to Shared Ledger' to see how signed custody events and an agreed validation process can give the parties one accepted record. Sensors, audits, contracts, and identity controls still connect that record to the real shipment.",
				"Now let's contrast when you need a database versus when you need a blockchain.",
			),
		},
		{
			id: "database-or-blockchain",
			kind: "comparison",
			section: "hook",
			sectionLabel: "03 · Architectural Contrast",
			durationSeconds: 105,
			title: "Database vs. Blockchain",
			left: {
				label: "Single Organization (Database)",
				steps: ["College ERP", "PostgreSQL", "Student Query"],
				caption: "Usually faster, simpler, and more private when one trusted organization owns and governs the system.",
			},
			right: {
				label: "Multi-Party Consortium (Blockchain)",
				steps: ["College", "Employer", "University", "Shared Cryptographic Proof"],
				caption: "Tamper-evident and verifiable when independently governed parties need common history without a single administrator.",
			},
			sourceIds: ["nist-fit"],
			notes: notes(
				"My architecture rule is simple: start with a database. Consider a shared ledger only when multiple independently governed parties must write or verify the same history, no neutral operator is acceptable, and the audit value justifies the extra governance, security, privacy, and performance cost.",
				"Let's summarize blockchain in one precise sentence.",
			),
		},

		// 10-15: FOUNDATIONS & THE ATOMIC PIECES
		{
			id: "one-sentence",
			kind: "statement",
			section: "foundations",
			sectionLabel: "04 · Foundations",
			durationSeconds: 75,
			eyebrow: "Blockchain in One Engineering Sentence",
			title: "A SHARED, TAMPER-EVIDENT LEDGER",
			statement: "Maintained by multiple independently governed participants.",
			fragments: ["Shared State", "Tamper-Evident", "Cryptographic Link", "Consensus Rules"],
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Notice what is not in this definition: trading, token prices, or hype. 'Shared' means authorized participants can hold or verify the record. 'Tamper-evident' means changing stored data creates a mismatch when the system recomputes and validates it. It does not mean the physical world is automatically truthful or that administrators have no power.",
				"Let's trace what happens when you click SEND.",
			),
		},
		{
			id: "transaction-journey",
			kind: "flow",
			section: "foundations",
			sectionLabel: "05 · Data Flow",
			durationSeconds: 120,
			title: "What happens after you click SEND?",
			steps: ["Transaction Proposal", "Peer Broadcast", "Cryptographic Validation", "Block Packaging", "Hash Linking", "Consensus Commit"],
			callout: "A typical permissioned flow: propose → validate → order → commit → replicate.",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"This is a simplified permissioned-ledger flow, not a universal protocol. A client proposes a signed transaction; authorized peers validate it; an ordering or consensus process establishes accepted sequence; the transaction is packaged and linked; replicas then converge on the committed state. Public networks implement these stages differently.",
				"Let's look at the foundational cryptographic primitive that makes this possible: the SHA-256 Hash.",
			),
		},
		{
			id: "hash-avalanche-demo",
			kind: "demo",
			demoId: "hash",
			section: "foundations",
			sectionLabel: "06 · Cryptography Lab",
			durationSeconds: 150,
			title: "ONE CHARACTER CHANGES EVERYTHING",
			callout: "Live browser SHA-256 · Same UTF-8 input, same 32-byte digest",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"This is real SHA-256 running locally through the browser's Web Crypto API. Change ₹10,000 to ₹10,001. The digest becomes unpredictably different; a well-designed cryptographic hash aims for roughly half of its output bits to change on average when the input changes slightly. The demo detects a changed message—it does not identify who changed it.",
				"Now let's see how this hash connects one block to the next.",
			),
		},
		{
			id: "block-anatomy",
			kind: "diagram",
			diagramId: "block-anatomy",
			section: "foundations",
			sectionLabel: "07 · Block Anatomy",
			durationSeconds: 90,
			title: "Inside One Block",
			callout: "SIMPLIFIED CLASSROOM BLOCK · DATA + PREVIOUS HASH + CALCULATED HASH",
			notes: notes(
				"This is a deliberately simplified block, not the complete schema of Bitcoin, Ethereum, or an enterprise ledger. Open each field. Its own digest fingerprints the serialized block data; the previous-hash value links this block to the fingerprint accepted for the block before it.",
				"Let's see what happens when multiple blocks are linked together.",
			),
		},
		{
			id: "chain-links",
			kind: "diagram",
			diagramId: "chain-links",
			section: "foundations",
			sectionLabel: "08 · The Chain",
			durationSeconds: 90,
			title: "Every Block Remembers The One Before",
			callout: "Change Block #1 → Block #2 still points to the old fingerprint",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Click 'Tamper Block #1'. Block #1's stored hash no longer matches its recomputed hash. Block #2 still points to the previously accepted value, so validation exposes a broken link. Later blocks may still have locally correct stored hashes, but trust in the history through them is invalid because the upstream chain failed.",
				"How do independent computers across the world agree on which blocks are valid?",
			),
		},
		{
			id: "consensus-network",
			kind: "demo",
			demoId: "consensus-flow",
			section: "foundations",
			sectionLabel: "09 · Consensus Lab",
			durationSeconds: 150,
			title: "HOW DOES A NETWORK AGREE?",
			callout: "Interactive 5-Node Consensus · Propose → Validate → Agree → Commit",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Use the selector before advancing. Permissioned BFT, proof of stake, and proof of work do not share one voting algorithm. This visual compares their broad coordination roles: proposing a candidate, independently checking protocol rules, reaching protocol-specific acceptance or confidence, and allowing replicas to converge. The exact thresholds, timing, and finality differ by network.",
				"Now let's make a critical industry distinction that every student must understand.",
			),
		},
		{
			id: "blockchain-not-crypto",
			kind: "diagram",
			diagramId: "branching-tree",
			section: "foundations",
			sectionLabel: "10 · Major Visual Statement",
			durationSeconds: 105,
			eyebrow: "Enterprise Clarification",
			title: "BLOCKCHAIN ≠ CRYPTOCURRENCY",
			callout: "Cryptocurrency is one application; shared ledgers also support settlement, provenance, and verification.",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Keep the categories separate. A blockchain is a data and coordination architecture. A cryptocurrency is a digitally native asset and incentive system that may use one. Institutional settlement, government record verification, and supply-chain provenance use different governance and permission models; we will label the actual maturity of each example later.",
				"Let's examine how the Web evolved to this point.",
			),
		},
		{
			id: "web-evolution",
			kind: "demo",
			demoId: "web-evolution",
			section: "foundations",
			sectionLabel: "11 · Web Architecture",
			durationSeconds: 105,
			title: "THE EVOLUTION OF THE WEB",
			callout: "Web1 published pages · Web2 built participatory platforms · Web3 explores user-held keys and verifiable state",
			sourceIds: ["ethereum-web3", "w3c-vc-2"],
			notes: notes(
				"This three-era model is a teaching shortcut, not a clean historical boundary. Web1 mostly published pages. Web2 made participation and platform databases central. Web3 is an umbrella term for designs where some identity, credentials, assets, or state can be verified beyond one platform. W3C Verifiable Credentials show that portability can use open cryptographic standards; a blockchain is optional, not automatic.",
				"Let's see how cryptographic identity works with digital signatures.",
			),
		},
		{
			id: "digital-signature",
			kind: "demo",
			demoId: "signature",
			section: "demo",
			sectionLabel: "12 · Signature Lab",
			durationSeconds: 105,
			title: "SIGN IT. THEN TRY TO FAKE IT.",
			callout: "Browser ECDSA P-256 Keypair · Private Key Signs · Public Key Verifies",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"A known hash helps detect a changed message. A digital signature adds evidence that the corresponding private key signed that exact message. Click 'Create key + sign', edit the identifier, and verify again. A mismatch is not, by itself, proof of who attacked it; real identity also depends on trustworthy key issuance, custody, rotation, and recovery.",
				"Now, let's combine hashes, links, and signatures for our centerpiece live attack.",
			),
		},

		// 15-30: THE WOW MOMENT – LIVE TAMPER ATTACK
		{
			id: "tamper-prediction",
			kind: "question",
			section: "demo",
			sectionLabel: "13 · Interactive Prediction",
			title: "Prediction: Attack on Block #2",
			durationSeconds: 60,
			question: "What will this local verifier report if Block #2 changes from 100 boxes to 1,000 after its hash was stored?",
			options: [
				"Only Block #2 fails",
				"Block #2 fails AND downstream trust collapses",
				"The network automatically accepts the change",
			],
			correctIndex: 1,
			explanation: "Block #2's recomputed hash no longer matches its stored hash. Block #3 still links to the previously accepted fingerprint, so the verifier marks the history from that point onward as untrusted.",
			notes: notes(
				"Ask everyone to choose before revealing the answer. This is a prediction check, not a measured classroom poll.",
				"Now, let's run the attack live in the integrity lab.",
			),
		},
		{
			id: "integrity-lab-wow",
			kind: "demo",
			demoId: "integrity",
			section: "demo",
			sectionLabel: "14 · Live Integrity Lab",
			durationSeconds: 150,
			title: "⚡ LIVE BLOCKCHAIN TAMPER ATTACK",
			callout: "Click TAMPER to break the chain · Click RESTORE to repair cryptographic trust",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Click 'Tamper with Block #2'. Block #2's stored and recomputed hashes diverge; Block #3 retains the earlier pointer; later history is marked untrusted because an upstream check failed. Restore copies the original classroom transaction back and verifies again. Tamper-evident means validation can expose an inconsistent history. Hiding a rewrite in a real network also depends on permissions, consensus, key security, and governance.",
				"Now let's add programmable business rules to that shared chain.",
			),
		},
		{
			id: "smart-contract-demo",
			kind: "demo",
			demoId: "smart-contract",
			section: "demo",
			sectionLabel: "15 · Smart Contracts",
			durationSeconds: 120,
			title: "RULES BECOME EXECUTABLE CODE",
			callout: "LOCAL RULE SIMULATION · IF received + quality passed + not expired → release condition met",
			sourceIds: ["ethereum-contracts"],
			notes: notes(
				"This slide demonstrates deterministic business-rule evaluation in the browser; it is not a deployed smart contract and no money moves. Toggle the inputs and the same inputs always produce the same decision. A production contract would still need authenticated data sources, access control, audit, upgrade policy, dispute handling, and integration with a real settlement system.",
				"Let's see how smart contracts fit inside real enterprise software architecture.",
			),
		},
		{
			id: "enterprise-architecture",
			kind: "demo",
			demoId: "enterprise-arch-flow",
			section: "demo",
			sectionLabel: "16 · Systems Architecture",
			durationSeconds: 120,
			title: "BLOCKCHAIN IS A COMPONENT",
			callout: "Next.js UI → FastAPI Gateway → ERP / SQL Database + Blockchain Settlement",
			notes: notes(
				"The proportion is different in every system, but the pattern is consistent: user experience, identity, private records, search, analytics, and integrations usually remain in conventional software. A ledger carries only the cross-organization events that justify shared validation. Keep sensitive data off the ledger where possible; use permissions, hashes, or pointers only after privacy and legal review.",
				"So when should an engineer actually use blockchain?",
			),
		},
		{
			id: "decision-tree",
			kind: "demo",
			demoId: "decision-tree",
			section: "demo",
			sectionLabel: "17 · Engineering Judgment",
			durationSeconds: 120,
			title: "WHEN NOT TO USE BLOCKCHAIN",
			callout: "Interactive 4-Step Architecture Diagnostic: Blockchain vs. Database",
			sourceIds: ["nist-fit"],
			notes: notes(
				"Walk through the four questions. They are a filter, not a procurement formula. A 'no' usually points toward a database or signed API. Four 'yes' answers only mean a ledger may deserve deeper evaluation; privacy, throughput, regulation, governance, operational ownership, and an exit plan still decide whether it should be built.",
				"Now let's examine blockchain in Finance and Banking.",
			),
		},

		// 30-45: FINANCE & SUPPLY CHAIN INDUSTRY PRODUCTION
		{
			id: "finance-intro",
			kind: "hero",
			section: "finance",
			sectionLabel: "18 · Finance Rails",
			durationSeconds: 60,
			eyebrow: "Industry Vertical 01 · Global Banking",
			title: "FINANCE MOVES VALUE",
			lines: ["PAYMENTS", "SETTLEMENT", "TOKENIZATION"],
			callout: "Cross-border improvement is measured in cost, speed, access, and transparency—not by whether a blockchain was used.",
			image: {
				src: "/images/lectures/institutional-settlement.webp",
				alt: "Institutional banking core connected via shared programmable settlement rails",
			},
			sourceIds: ["fsb-cross-border-targets", "bis-tokenisation-vision"],
			notes: notes(
				"The G20 cross-border-payment programme defines outcomes: lower cost, greater speed, wider access, and more transparency. It does not prescribe blockchain. Shared programmable ledgers are one architecture being explored where multiple regulated institutions must coordinate money, assets, and settlement conditions.",
				"Compare an illustrative multi-ledger route with a shared programmable rail.",
			),
		},
		{
			id: "settlement-compare",
			kind: "diagram",
			diagramId: "settlement-flow",
			section: "finance",
			sectionLabel: "19 · Settlement Rails",
			durationSeconds: 105,
			title: "Traditional vs. Programmable Settlement",
			callout: "Illustrative multi-ledger route vs. shared programmable rail · Timing and finality depend on design",
			image: {
				src: "/images/lectures/programmable-finance-infographic.webp",
				alt: "Concept comparison of a multi-ledger payment route and a shared programmable settlement rail",
			},
			sourceIds: ["fsb-cross-border-targets", "bis-tokenisation-vision"],
			notes: notes(
				"The left is an illustrative route across institutions and ledgers; actual corridors differ. The right shows the design goal of bringing messaging, reconciliation, and settlement conditions closer together. BIS describes tokenisation and unified-ledger concepts as a blueprint. It is not evidence that every transfer is instant or that every asset has final legal settlement on a blockchain.",
				"Let's look at the real-world bank doing this in production right now.",
			),
		},
		{
			id: "kinexys-case",
			kind: "sources",
			section: "finance",
			sectionLabel: "20 · Production Case Study",
			durationSeconds: 90,
			eyebrow: "Production Institutional Rail · J.P. Morgan",
			title: "J.P. Morgan Kinexys",
			items: [
				{
					title: "$3 Trillion+ Total Volume Processed",
					detail: "Over $5 Billion average daily volume moving institutional money 24/7 across global banking participants.",
					status: "production",
					sourceId: "kinexys",
				},
				{
					title: "Project Agorá · BIS-Led Prototype",
					detail: "A public-private exploration of tokenised commercial bank deposits and wholesale central bank money. Controlled real-value testing is evidence of progress—not a finished global product.",
					status: "prototype",
					sourceId: "bis-agora",
				},
			],
			sourceIds: ["kinexys", "bis-agora"],
			notes: notes(
				"J.P. Morgan reports that Kinexys has processed more than three trillion US dollars since inception and averages more than five billion dollars daily. That is a production permissioned rail. Beside it, Agorá remains a prototype. Showing both labels is how we separate demonstrated operation from promising research.",
				"What about India's central bank digital currency?",
			),
		},
		{
			id: "digital-rupee",
			kind: "sources",
			section: "finance",
			sectionLabel: "21 · Digital Rupee Pilot",
			durationSeconds: 90,
			eyebrow: "Reserve Bank of India (RBI)",
			title: "e₹ · Digital Rupee",
			items: [
				{
					title: "Retail (e₹-R) & Wholesale (e₹-W) Pilots",
					detail: "RBI is piloting programmable digital cash, offline transaction capability, and interbank settlement.",
					status: "pilot",
					sourceId: "rbi-cbdc",
				},
				{
					title: "DTCC Digital Assets Tokenization",
					detail: "DTCC has demonstrated live production trades, while the broader tokenisation service remains labelled prelaunch with rollout expected later in 2026.",
					status: "prelaunch",
					sourceId: "dtcc-tokenization",
				},
			],
			notes: notes(
				"Notice the official label from RBI: Pilot. As software engineers, always distinguish between Production, Pilot, Prototype, and Prelaunch. Do not oversell a pilot as completed production.",
				"Let's review the 2026 industry maturity matrix.",
			),
		},
		{
			id: "finance-maturity",
			kind: "demo",
			demoId: "industry-reality",
			section: "finance",
			sectionLabel: "22 · Industry Reality Matrix",
			durationSeconds: 105,
			title: "WHAT DOES THE EVIDENCE SHOW IN 2026?",
			callout: "Production ≠ Pilot ≠ Prototype ≠ Prelaunch ≠ Closed",
			sourceIds: ["kinexys", "rbi-cbdc", "bis-agora", "dtcc-tokenization", "india-live-chains", "india-nbf", "walmart-traceability", "tradelens-closure", "google-ap2", "coinbase-x402"],
			notes: notes(
				"Click across Finance, India, Supply Chain, and AI Agents. This matrix teaches students how to evaluate technology claims objectively.",
				"Now let's move to our second major vertical: Supply Chain & Medicine Logistics.",
			),
		},
		{
			id: "medicine-journey",
			kind: "demo",
			demoId: "supply-chain",
			section: "supply-chain",
			sectionLabel: "23 · Supply Chain Lab",
			durationSeconds: 120,
			title: "FOLLOW BATCH PCM-001",
			callout: "Classroom batch: manufacturer → distributor → warehouse → hospital → dispensing desk",
			image: {
				src: "/images/lectures/pharma-provenance-infographic.webp",
				alt: "Concept illustration of pharmaceutical custody records from factory to dispensing",
			},
			notes: notes(
				"This is a fixed classroom scenario, not a live shipment. Move through the five custody records, then edit the distributor quantity. The verifier detects that the stored event and accepted fingerprint no longer agree. That proves record inconsistency; it does not prove what was physically inside the box. Production provenance needs trusted identities, scanning, sensors, audits, and exception handling.",
				"Let's look at India's live government deployment in medicine logistics.",
			),
		},
		{
			id: "india-drug-logistics",
			kind: "sources",
			section: "supply-chain",
			sectionLabel: "24 · Live Indian Deployment",
			durationSeconds: 75,
			eyebrow: "National Blockchain Portal · NIC",
			title: "Drug Logistics Chain",
			items: [
				{
					title: "Manufacturer / Supplier → Warehouse → Hospital",
					detail: "NIC lists Drug Logistics as a live chain connecting medicine suppliers, warehouses, and hospitals for shared logistics records.",
					status: "production",
					sourceId: "india-drug-logistics",
				},
			],
			notes: notes(
				"The National Blockchain Portal labels Drug Logistics as a live chain. That supports a production-maturity claim for the digital record system. It does not, on its own, prove the absence of counterfeit products or replace physical quality controls.",
				"Let's also learn from a major corporate failure: TradeLens.",
			),
		},
		{
			id: "supply-chain-lessons",
			kind: "sources",
			section: "supply-chain",
			sectionLabel: "25 · Enterprise Case Study",
			durationSeconds: 90,
			title: "Adoption Is Part of Architecture",
			items: [
				{
					title: "Walmart Leafy Greens Traceability",
					detail: "Walmart reported in 2018 that a trace which could take about seven days was reduced to a few seconds.",
					status: "deployment",
					sourceId: "walmart-traceability",
				},
				{
					title: "TradeLens (IBM + Maersk) Discontinued",
					detail: "Maersk announced discontinuation after the platform did not achieve the commercial viability and level of industry collaboration needed to continue.",
					status: "closed",
					sourceId: "tradelens-closure",
				},
			],
			notes: notes(
				"These two cases keep the lecture honest. Walmart documented a major traceability improvement in 2018. TradeLens later closed because the collaboration did not reach commercial viability. The defensible lesson is not that one company caused the failure; it is that multi-party infrastructure needs sustainable participation, incentives, governance, and operations as well as sound code.",
				"Let's look at India's national infrastructure stack: Vishvasya.",
			),
		},

		// 45-55: BEYOND & AI CONVERGENCE
		{
			id: "vishvasya-india",
			kind: "sources",
			section: "beyond",
			sectionLabel: "26 · National Infrastructure",
			durationSeconds: 75,
			eyebrow: "MeitY Government Infrastructure · India",
			title: "VISHVASYA",
			items: [
				{
					title: "National Blockchain Framework (BaaS)",
					detail: "Launched in September 2024 by MeitY with geographically distributed infrastructure in Bhubaneswar, Pune, and Hyderabad.",
					status: "production",
					sourceId: "india-nbf",
				},
			],
			notes: notes(
				"Vishvasya is a permissioned Blockchain-as-a-Service infrastructure for government use. The platform is production infrastructure; that label does not automatically make every application built on it a production deployment. Each application still needs its own evidence, governance, security, and adoption assessment.",
				"Let's see one live citizen use case every student in this room has touched: CBSE certificates.",
			),
		},
		{
			id: "cbse-credentials",
			kind: "sources",
			section: "beyond",
			sectionLabel: "27 · Education Credentials",
			durationSeconds: 75,
			eyebrow: "Academic Document Chain · CBSE",
			title: "Verify The Credential, Not A Photocopy",
			items: [
				{
					title: "CBSE Academic Documents · Certificate Chain",
					detail: "NIC lists CBSE academic documents within its live Certificate Chain, enabling a verifier to check a record against the issuer-backed system.",
					status: "production",
					sourceId: "india-cbse",
				},
			],
			sourceIds: ["india-cbse", "w3c-vc-2"],
			notes: notes(
				"The defensible claim is narrower than 'all degrees are on blockchain.' NIC lists CBSE academic documents on its production Certificate Chain. More broadly, W3C Verifiable Credentials standardize machine-verifiable credentials without requiring a blockchain. Architecture should follow the issuer, privacy, revocation, and interoperability requirements.",
				"Let's explore the multi-industry ecosystem wheel.",
			),
		},
		{
			id: "beyond-ecosystem-radial",
			kind: "demo",
			demoId: "ecosystem-radial",
			section: "beyond",
			sectionLabel: "28 · Multi-Industry Radial",
			durationSeconds: 120,
			title: "THE MULTI-INDUSTRY ECOSYSTEM",
			callout: "Eight documented systems · Compare the coordination problem, ledger role, and maturity label",
			sourceIds: ["kinexys", "india-drug-logistics", "india-cbse", "india-property", "india-live-chains", "india-nbf", "bis-agora", "google-ap2", "coinbase-x402"],
			notes: notes(
				"Explore all eight systems. Do not flatten them into one success story: Kinexys is production; NIC lists several live government chains; Vishvasya is production infrastructure; Agorá is a prototype; AP2 and x402 are emerging protocol work. The maturity label is part of the engineering evidence.",
				"Now let's look at the future: the intersection of AI Agents and Blockchain.",
			),
		},
		{
			id: "ai-blockchain-convergence",
			kind: "demo",
			demoId: "ai-convergence",
			section: "beyond",
			sectionLabel: "29 · AI × Blockchain",
			durationSeconds: 150,
			title: "AI ACTS. BLOCKCHAIN PROVES.",
			callout: "2030 design scenario · AI proposes · policy constrains · credentials authorize · settlement records",
			image: {
				src: "/images/lectures/ai-agent-blockchain-infographic.webp",
				alt: "Concept illustration of an AI proposal passing through policy, authorization, and an optional shared settlement record",
			},
			sourceIds: ["google-ap2", "coinbase-x402"],
			notes: notes(
				"Treat this as a 2030 design scenario, not a forecast that every AI agent will use blockchain. A model can propose an action; deterministic policy can limit budget and suppliers; a signed mandate can show what the user authorized; a payment protocol can carry a request; and a shared ledger may record settlement when independently governed parties need it. AP2 and x402 illustrate different parts of that emerging stack, not one universal deployed system.",
				"Let's test what we've learned with a final architecture question.",
			),
		},
		{
			id: "quiz-crypto-vs-blockchain",
			kind: "question",
			section: "beyond",
			sectionLabel: "30 · Final Architecture Poll",
			title: "Architecture Poll: Where Does Blockchain Fit?",
			durationSeconds: 60,
			question: "Which of the following problems MOST genuinely justifies building on a blockchain?",
			options: [
				"A university canteen lunch pre-order app",
				"Cross-border pharmaceutical anti-counterfeit traceability across 4 countries",
				"A high-speed real-time multiplayer 3D video game",
			],
			correctIndex: 1,
				explanation: "The cross-border pharmaceutical case has the strongest reason to evaluate a shared ledger: independently governed parties, shared custody records, and high audit requirements. It still needs physical-world evidence and governance. The other two examples are usually better served by conventional databases.",
			notes: notes(
				"Reveal the answer only after the room commits. The point is not that blockchain is mandatory; it is that only the pharmaceutical case earns a serious ledger evaluation. Good engineers can reject an exciting technology when the fit is weak.",
				"Let's discuss why this skill commands a premium in software engineering.",
			),
		},

		// 55-60: CAREER ROADMAP & INSPIRATIONAL CLOSING
		{
			id: "why-premium-engineers",
			kind: "cards",
			section: "career",
			sectionLabel: "31 · Career Value",
			durationSeconds: 105,
			title: "WHY CAN THIS WORK COMMAND A PREMIUM?",
			items: [
				{ title: "Rare Intersection", detail: "Distributed systems + cryptography + security + enterprise finance." },
				{ title: "High Financial Stakes", detail: "A tiny smart contract bug can expose millions in real funds. Precision engineering is mandatory." },
				{ title: "Governed State", detail: "Protocol and contract changes require careful migration, authorization, and participant coordination." },
				{ title: "AI-Era Controls", detail: "Emerging agent systems need scoped authority, verifiable intent, policy enforcement, and auditable payments." },
				{ title: "Production Ownership", detail: "Consensus nodes, key management, telemetry, and distributed incident response." },
				{ title: "Business Translation", detail: "Engineers who can clearly explain governance, regulation, and architecture tradeoffs." },
			],
			callout: "Career value comes from scarce engineering judgment—not merely writing Solidity syntax.",
			sourceIds: ["wef-future-jobs"],
			notes: notes(
				"No report guarantees a blockchain salary. The World Economic Forum's employer survey does place FinTech Engineers among the fastest-growing roles to 2030 and expects almost 40 percent of core skills to change. The durable opportunity is the intersection: distributed systems, security, cryptography, finance, governance, and the ability to explain trade-offs clearly.",
				"Here is your concrete roadmap starting from BCA Year 1.",
			),
		},
		{
			id: "career-roadmap",
			kind: "cards",
			section: "career",
			sectionLabel: "32 · Student Roadmap",
			durationSeconds: 120,
			eyebrow: "BCA Year 1 · Master in this sequence",
			title: "YOUR SYSTEMS ROADMAP STARTS TODAY",
			image: {
				src: "/images/lectures/bca-systems-roadmap-infographic.webp",
				alt: "BCA 1st Year Systems Roadmap: Programming, Networks, Cryptography, Blockchain, Smart Contracts & AI Agents",
			},
			items: [
				{ title: "01 · Programming & Data Structures", detail: "TypeScript or Python, Git, memory structures, algorithms, and linked lists." },
				{ title: "02 · Systems & Networks", detail: "HTTP, TCP/IP, client-server models, REST APIs, Linux, and PostgreSQL." },
				{ title: "03 · Applied Cryptography", detail: "SHA-256 hashes, symmetric AES, asymmetric RSA/ECDSA, and public-key infrastructure." },
				{ title: "04 · Blockchain Foundations", detail: "Build a small local hash-linked chain in TypeScript; understand validation, consensus, and state." },
				{ title: "05 · Smart Contracts & EVM", detail: "Write deterministic business logic; test edge-cases, vulnerabilities, and unit tests." },
				{ title: "06 · AI & Agent Orchestration", detail: "Connect LLM reasoning agents to verifiable API tools and scoped payment wallets." },
			],
			callout: "First Year Portfolio: Build this lecture's hash-linked chain locally in TypeScript.",
			notes: notes(
				"Start with engineering, not speculation. Write TypeScript, build the local chain used in this lecture, test tampering, then add a policy layer that requires human approval before an AI-proposed action. That portfolio shows judgment because it includes both the mechanism and its limits.",
				"Close by separating the 2030 horizon from what is already proven today.",
			),
		},
		{
			id: "four-truths",
			kind: "cards",
			section: "closing",
			sectionLabel: "33 · 2030 Outlook",
			durationSeconds: 75,
			title: "WHAT TO WATCH ON THE ROAD TO 2030",
			items: [
				{ title: "1. Regulated Tokenised Finance", detail: "Track which experiments move from prototypes into repeatable, legally final production settlement." },
				{ title: "2. Verifiable Credentials", detail: "Expect more machine-verifiable records; evaluate when issuer signatures are enough and when a shared registry helps." },
				{ title: "3. Agents With Scoped Authority", detail: "AI payment systems must make user intent, spending limits, identity, and accountability explicit." },
				{ title: "4. Hybrid Architecture", detail: "Cloud databases will remain central; use ledgers only for the shared events that justify the cost." },
			],
			callout: "2030 is a design horizon, not a promise. Watch what moves from prototype to repeatable production.",
			sourceIds: ["bis-tokenisation-vision", "w3c-vc-2", "google-ap2", "coinbase-x402", "wef-future-jobs"],
			notes: notes(
				"This is not a coin-price prediction or a promise that blockchain replaces the web. It is a watchlist. By 2030, ask which tokenised-finance experiments achieved legal and operational scale, which credentials became portable, which controls made AI-agent payments safe, and where hybrid systems proved better than all-on-chain designs.",
				"Let's close with our final challenge and the live student takeaway.",
			),
		},
		{
			id: "final-challenge-qr",
			kind: "demo",
			demoId: "qr-takeaway",
			section: "closing",
			sectionLabel: "34 · Student Takeaway & Challenge",
			durationSeconds: 120,
			title: "BUILD FOR 2030. VERIFY TODAY.",
			callout: "Choose one real coordination problem. Prove the need before choosing the ledger.",
			notes: notes(
				"Scan the QR code and reopen the same labs on your phone. Reproduce the hash, break the local chain, restore it, and explain why the smart-contract screen is only a simulation. Then choose one real multi-party problem and write down the governance, data, privacy, and failure assumptions before writing code. That habit—not a buzzword—is what makes an engineer ready for 2030. Thank you.",
				"Open the floor for questions from BCA Year 1 students.",
			),
		},
	],
};
