import type { Lecture } from "@/lib/lectures/types";

const notes = (
	say: string,
	transition: string,
	ask?: string,
	expected?: string,
) => ({ say, transition, ask, expected });

export const blockchainLecture: Lecture = {
	slug: "blockchain-finance-supply-chain",
	shortTitle: "Blockchain: Finance, Supply Chain & Beyond",
	title: "Blockchain Applications in Finance, Supply Chain & Beyond",
	description:
		"A beginner-first 60-minute visual lecture connecting blockchain fundamentals, Web3, real 2026 industry systems, premium engineering skills, and the emerging AI-agent economy.",
	audience: "BCA 1st Year · Kristu Jayanti University, Bengaluru",
	presenter: "Manoj Mukherjee · Founder · AI Scientist · Enterprise AI Architect",
	totalMinutes: 60,
	sources: [
		{
			id: "nist-blockchain",
			label: "Blockchain overview",
			publisher: "US National Institute of Standards and Technology",
			url: "https://www.nist.gov/blockchain",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "nist-fit",
			label: "Privacy-Enhancing Lightweight Distributed Ledger Technology",
			publisher: "NIST Computer Security Resource Center",
			url: "https://csrc.nist.gov/projects/privacy-enhancing-lw-distributed-ledger-technology",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "ethereum-contracts",
			label: "Introduction to smart contracts",
			publisher: "Ethereum.org",
			url: "https://ethereum.org/developers/docs/smart-contracts/",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "ethereum-web3",
			label: "Introduction to Web3",
			publisher: "Ethereum.org",
			url: "https://ethereum.org/web3/",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "wef-future-jobs",
			label: "Future of Jobs Report 2025",
			publisher: "World Economic Forum",
			url: "https://www.weforum.org/publications/the-future-of-jobs-report-2025/in-full/2-jobs-outlook/",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "electric-developers",
			label: "2024 Crypto Developer Report",
			publisher: "Electric Capital",
			url: "https://www.developerreport.com/developer-report",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "google-ap2",
			label: "Agent Payments Protocol and Verifiable Intent",
			publisher: "Google",
			url: "https://blog.google/products-and-platforms/platforms/google-pay/agent-payments-protocol-fido-alliance/",
			status: "reference",
			verifiedAt: "2026-08-21",
		},
		{
			id: "coinbase-x402",
			label: "x402 protocol for programmatic payments",
			publisher: "Coinbase Developer Platform",
			url: "https://docs.cdp.coinbase.com/x402/welcome",
			status: "deployment",
			verifiedAt: "2026-08-21",
		},
		{
			id: "india-nbf",
			label: "Vishvasya Blockchain Technology Stack launch",
			publisher: "Ministry of Electronics and Information Technology / PIB",
			url: "https://www.pib.gov.in/PressReleseDetailm.aspx?PRID=2051934&lang=2&reg=48",
			status: "production",
			verifiedAt: "2026-08-21",
		},
		{
			id: "india-live-chains",
			label: "National Blockchain Portal dashboard",
			publisher: "NIC Centre of Excellence in Blockchain Technology",
			url: "https://www.blockchain.gov.in/Home/Home",
			status: "production",
			verifiedAt: "2026-08-21",
		},
		{
			id: "india-cbse",
			label: "CBSE Certificate Chain",
			publisher: "NIC Centre of Excellence in Blockchain Technology",
			url: "https://www.blockchain.gov.in/Home/Users?user=CBSC",
			status: "production",
			verifiedAt: "2026-08-21",
		},
		{
			id: "india-property",
			label: "Property Chain",
			publisher: "NIC Centre of Excellence in Blockchain Technology",
			url: "https://www.blockchain.gov.in/Home/LiveChain?LiveChain=PropertyChain",
			status: "production",
			verifiedAt: "2026-08-21",
		},
		{
			id: "rbi-cbdc",
			label: "RBI Annual Report 2024–25 · FinTech Department",
			publisher: "Reserve Bank of India",
			url: "https://www.rbi.org.in/scripts/AnnualReportPublications.aspx?Id=1436",
			status: "pilot",
			verifiedAt: "2026-08-21",
		},
		{
			id: "kinexys",
			label: "Latest milestones at Kinexys",
			publisher: "J.P. Morgan",
			url: "https://www.jpmorgan.com/payments/newsroom/kinexys-milestones-2026",
			status: "production",
			verifiedAt: "2026-08-21",
		},
		{
			id: "bis-agora",
			label: "Project Agorá",
			publisher: "Bank for International Settlements",
			url: "https://www.bis.org/about/bisih/topics/fmis/agora.htm",
			status: "prototype",
			verifiedAt: "2026-08-21",
		},
		{
			id: "dtcc-tokenization",
			label: "Tokenization becomes a reality",
			publisher: "DTCC",
			url: "https://www.dtcc.com/digital-assets/tokenization/live-production-trades",
			status: "prelaunch",
			verifiedAt: "2026-08-21",
		},
		{
			id: "walmart-traceability",
			label: "Walmart deploys blockchain to track leafy greens",
			publisher: "Walmart",
			url: "https://corporate.walmart.com/news/2018/09/24/in-wake-of-romaine-e-coli-scare-walmart-deploys-blockchain-to-track-leafy-greens",
			status: "deployment",
			verifiedAt: "2026-08-21",
		},
		{
			id: "tradelens-closure",
			label: "Information on the closure of TradeLens",
			publisher: "A.P. Moller–Maersk",
			url: "https://www.maersk.com/news/articles/2022/12/01/information-on-the-closure-of-tradeLens",
			status: "closed",
			verifiedAt: "2026-08-21",
		},
		{
			id: "eu-ebsi",
			label: "European Blockchain Services Infrastructure",
			publisher: "European Commission",
			url: "https://digital-strategy.ec.europa.eu/en/policies/european-blockchain-services-infrastructure",
			status: "deployment",
			verifiedAt: "2026-08-21",
		},
	],
	scenes: [
		{
			id: "opening",
			kind: "hero",
			section: "hook",
			sectionLabel: "Hook",
			durationSeconds: 45,
			eyebrow: "Kristu Jayanti University · BCA Year 1",
			title: "Blockchain Applications",
			lines: ["FINANCE", "SUPPLY CHAIN", "& BEYOND"],
			callout: "Manoj Mukherjee · Founder · AI Scientist · Enterprise AI Architect",
			image: {
				src: "/images/lectures/blockchain-ai-network.webp",
				alt: "Abstract linked data blocks connected across distributed computer nodes with an AI signal joining the network",
				preload: true,
			},
			notes: notes(
				"Do not begin with a definition. I build software, AI and enterprise systems, so today we will operate blockchain like engineers: make a record, attack it, repair it, then challenge the industry claims.",
				"Open the shared-ledger lab. The first three minutes should make the word blockchain feel concrete.",
			),
		},
		{
			id: "shared-ledger-first",
			kind: "demo",
			demoId: "shared-ledger",
			section: "hook",
			sectionLabel: "Blockchain First",
			durationSeconds: 180,
			title: "ONE RECORD. FOUR COPIES.",
			callout: "Create → broadcast → validate → commit → try changing one copy",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Before defining blockchain, let the class operate one. Ask four students to imagine they each hold a copy of the same notebook, then advance one step at a time.",
				"Now contrast this shared notebook with the databases students already use.",
				"If Student B secretly changes 5 points to 50, can the other copies expose it?",
				"Yes. Replication makes the mismatch visible; blockchain adds cryptographic links and agreement rules.",
			),
		},
		{
			id: "database-or-blockchain",
			kind: "comparison",
			section: "hook",
			sectionLabel: "Blockchain First",
			durationSeconds: 120,
			title: "Database or blockchain?",
			left: { label: "One trusted owner", steps: ["College", "Database", "Students"], caption: "Fast, private and simple when one organization owns truth" },
			right: { label: "Independent participants", steps: ["College", "Employer", "University", "Shared proof"], caption: "Useful when no single participant should silently rewrite shared history" },
			sourceIds: ["nist-fit"],
			notes: notes(
				"A normal database is usually the correct answer when one trusted organization owns the system. Blockchain becomes interesting when independently governed parties need common state.",
				"With that mental model, the formal definition is now simple.",
				"Would you put your personal notes app on blockchain?",
				"No. One user, one owner and no shared-governance problem.",
			),
		},
		{
			id: "one-sentence",
			kind: "statement",
			section: "foundations",
			sectionLabel: "Foundations",
			durationSeconds: 75,
			eyebrow: "Blockchain in one sentence",
			title: "A SHARED, TAMPER-EVIDENT LEDGER",
			statement: "For multiple participants.",
			fragments: ["Shared", "Tamper-evident", "Ledger", "Participants"],
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Blockchain is a coordination architecture, not a coin. Shared means common history. Tamper-evident means a hidden change becomes detectable—not that bad data can never enter.",
				"Let us unpack the engineering pieces inside that sentence.",
			),
		},
		{
			id: "transaction-journey",
			kind: "flow",
			section: "foundations",
			sectionLabel: "Foundations",
			durationSeconds: 180,
			title: "What happens after you click SEND?",
			steps: ["Transaction", "Broadcast", "Validate", "Block", "Link", "Replicate"],
			callout: "A block is accepted history—not merely a box of data",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Walk from left to right. A proposed transaction is shared, checked against rules, grouped, cryptographically linked and copied across participants.",
				"The smallest cryptographic piece to understand is the hash.",
				"At which step does a proposal become accepted history?",
				"After validation and agreement, when it is committed into the chain.",
			),
		},
		{
			id: "hash-demo",
			kind: "demo",
			demoId: "hash",
			section: "foundations",
			sectionLabel: "Foundations",
			durationSeconds: 150,
			title: "One character changes everything",
			callout: "₹10,000 → ₹10,001",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"A hash is a fingerprint of data. It is not encryption, and it does not prove the input was truthful.",
				"Now use that fingerprint to connect one record to the next.",
				"Will one digit change a little of the hash or nearly all of it?",
				"Nearly all of it.",
			),
		},
		{
			id: "block-anatomy",
			kind: "diagram",
			diagramId: "block-anatomy",
			section: "foundations",
			sectionLabel: "Foundations",
			durationSeconds: 105,
			title: "Inside one block",
			callout: "DATA + PREVIOUS HASH + THIS HASH",
			notes: notes(
				"The block remembers its data and the fingerprint of the block before it.",
				"The previous-hash field turns independent blocks into a chain.",
				"What happens if its transaction changes?",
				"Its hash changes.",
			),
		},
		{
			id: "chain-link",
			kind: "diagram",
			diagramId: "chain-links",
			section: "foundations",
			sectionLabel: "Foundations",
			durationSeconds: 105,
			title: "Every block remembers the one before",
			callout: "Change Block 1 → Block 2 still points to the old fingerprint",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Changing Block 1 changes its fingerprint. Block 2 still points to the old fingerprint, exposing the break.",
				"A real network also needs rules for agreeing on valid state.",
			),
		},
		{
			id: "consensus",
			kind: "diagram",
			diagramId: "consensus-network",
			section: "foundations",
			sectionLabel: "Foundations",
			durationSeconds: 120,
			title: "How does the network agree?",
			callout: "Proof of Work · Proof of Stake · Permissioned validation",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Consensus is about valid shared state. Known enterprise participants commonly use permissioned validation rather than mining.",
				"This is why blockchain is bigger than cryptocurrency.",
				"Does every enterprise blockchain need mining?",
				"No.",
			),
		},
		{
			id: "web-evolution",
			kind: "demo",
			demoId: "web-evolution",
			section: "foundations",
			sectionLabel: "Web3",
			durationSeconds: 180,
			title: "WHY WEB3?",
			callout: "Web1: read · Web2: read/write · Web3: read/write/own or independently verify",
			sourceIds: ["ethereum-web3", "nist-blockchain"],
			notes: notes(
				"Let students switch between the three eras. Web3 is not a magic new browser; it is a family of architectures that move some identity, ownership, payments and verification into shared protocols.",
				"Now build and break the data structure that makes this possible.",
				"Does Web3 replace every Web2 application?",
				"No. Most useful systems will be hybrid, and decentralization exists on a spectrum.",
			),
		},
		{
			id: "digital-signature",
			kind: "demo",
			demoId: "signature",
			section: "demo",
			sectionLabel: "Live Demo",
			durationSeconds: 90,
			title: "SIGN IT. THEN TRY TO FAKE IT.",
			callout: "Private key signs · public key verifies · an edited message fails",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"A hash proves content integrity; a digital signature also connects approval to a private key. Sign the original message, verify it, then edit one character and verify again.",
				"Now place signed events into a chain where each block remembers the previous one.",
				"Should the private key ever be shared with the verifier?",
				"No. The verifier needs only the public key.",
			),
		},
		{
			id: "build-chain",
			kind: "flow",
			section: "demo",
			sectionLabel: "Live Demo",
			durationSeconds: 90,
			title: "BUILD THE JOURNEY",
			steps: ["Manufactured", "Distributed", "Received"],
			callout: "Every block inherits the previous block's hash",
			notes: notes(
				"Each organization adds an event; no one is rewriting a master spreadsheet.",
				"Before I attack it, predict what will happen.",
				"Which field proves Block 3 knows Block 2?",
				"Previous hash.",
			),
		},
		{
			id: "tamper-prediction",
			kind: "question",
			section: "demo",
			sectionLabel: "Live Demo",
			durationSeconds: 60,
			title: "Prediction",
			question: "What breaks if Block #2 changes from 100 to 1000?",
			options: ["Only Block 2", "Block 2 and downstream trust", "Nothing"],
			correctIndex: 1,
			explanation: "Block 2's stored hash stops matching its data; Block 3's previous link then points to the old fingerprint.",
			notes: notes(
				"Commit to an answer before the demo.",
				"Let us attack the history.",
				"Who predicts the damage will spread?",
				"A mixed response creates anticipation.",
			),
		},
		{
			id: "tamper-attack",
			kind: "demo",
			demoId: "integrity",
			section: "demo",
			sectionLabel: "Live Demo",
			durationSeconds: 150,
			title: "CREATE → LINK → TAMPER → RESTORE",
			callout: "The lecture's live integrity lab",
			sourceIds: ["nist-blockchain"],
			notes: notes(
				"Tamper-evident does not mean impossible to edit. It means an edit cannot remain hidden under normal validation.",
				"Detection matters only if we can return to a valid agreed state.",
			),
		},
		{
			id: "restore-chain",
			kind: "statement",
			section: "demo",
			sectionLabel: "Live Demo",
			durationSeconds: 60,
			title: "RESTORE → VERIFY",
			statement: "Validation compares what is stored with what should be true under agreed rules.",
			fragments: ["Stored", "Calculated", "Linked", "Valid"],
			notes: notes(
				"The restore action returns to the deterministic accepted history; every block verifies green again.",
				"We can also place business rules beside that shared history.",
			),
		},
		{
			id: "smart-contract",
			kind: "demo",
			demoId: "smart-contract",
			section: "demo",
			sectionLabel: "Live Demo",
			durationSeconds: 120,
			title: "RULES BECOME EXECUTABLE",
			callout: "Received AND quality passed AND not expired → release payment",
			sourceIds: ["ethereum-contracts"],
			notes: notes(
				"A smart contract is a program on a blockchain. It executes the logic developers wrote—including bugs if they wrote them.",
				"The hard question is not can we use blockchain; it is should we.",
				"What if a quality sensor sends false data?",
				"The program may confidently make the wrong decision.",
			),
		},
		{
			id: "decision-framework",
			kind: "cards",
			section: "demo",
			sectionLabel: "Live Demo",
			durationSeconds: 90,
			title: "Use blockchain when…",
			items: [
				{ title: "Multiple parties", detail: "Independent governance" },
				{ title: "Shared state", detail: "A common history is valuable" },
				{ title: "Limited trust", detail: "No single owner should control truth" },
				{ title: "Audit matters", detail: "Provenance and tamper evidence matter" },
			],
			callout: "One trusted owner + simple CRUD? Prefer a normal database.",
			sourceIds: ["nist-fit"],
				notes: notes(
					"Founder rule: if one company owns truth, use a database. Blockchain introduces governance, privacy, integration and operational costs; earn that complexity only when independently governed participants need the same state.",
				"Test this rule on a familiar company.",
			),
		},
		{
			id: "depends-poll",
			kind: "question",
			section: "demo",
			sectionLabel: "Live Demo",
			durationSeconds: 60,
			title: "Architecture poll",
			question: "Should Amazon use blockchain for every product record?",
			options: ["Yes", "No", "Depends"],
			correctIndex: 2,
			explanation: "Use it where independent parties need shared, auditable state—not for every internal query.",
			notes: notes(
				"Architecture is contextual. Depends is useful only when you can explain the conditions.",
				"Now see where those conditions appear in finance.",
			),
		},
		{
			id: "finance-intro",
			kind: "hero",
			section: "finance",
			sectionLabel: "Finance",
			durationSeconds: 60,
			eyebrow: "Industry system 01",
			title: "FINANCE MOVES VALUE",
			lines: ["PAYMENTS", "SETTLEMENT", "TOKENIZATION"],
			callout: "The valuable layer is invisible: synchronized records, programmable rules and final settlement.",
			image: {
				src: "/images/lectures/institutional-settlement.webp",
				alt: "Regulated financial institutions connected through a shared programmable settlement core",
			},
			notes: notes(
				"Enterprise blockchain in finance is mostly invisible infrastructure: moving money and assets under rules. It is closer to a settlement engine than a trading screen.",
				"The friction becomes visible in a cross-border payment.",
			),
		},
		{
			id: "settlement-compare",
			kind: "comparison",
			section: "finance",
			sectionLabel: "Finance",
			durationSeconds: 90,
			title: "Many steps. Many ledgers.",
			left: { label: "Traditional", steps: ["Bank A", "Correspondent", "Clearing", "Bank B", "Customer"], caption: "Separate messages, checks and settlement" },
			right: { label: "Shared rail", steps: ["Participant", "Programmable settlement", "Participant"], caption: "Coordinated records and rules" },
			notes: notes(
				"Blockchain does not erase regulation or banks. It can coordinate records and programmed settlement between known institutions.",
				"One bank-led network has already moved beyond experiments.",
			),
		},
		{
			id: "kinexys-case",
			kind: "sources",
			section: "finance",
			sectionLabel: "Finance",
			durationSeconds: 90,
			eyebrow: "Production · J.P. Morgan",
			title: "Kinexys: programmable institutional money",
			items: [{ title: "$3T+ since inception · $5B+ average daily", detail: "24/7 institutional payments, assets and programmable settlement—not speculative coins.", status: "production", sourceId: "kinexys" }],
			notes: notes(
				"J.P. Morgan reports more than three trillion dollars processed since inception and more than five billion dollars in average daily volume. This is the production signal: repeatable institutional use, operational controls and value moving every day.",
				"India is also testing programmable digital money, but its maturity label is different.",
			),
		},
		{
			id: "digital-rupee",
			kind: "sources",
			section: "finance",
			sectionLabel: "Finance",
			durationSeconds: 75,
			eyebrow: "Pilot · Reserve Bank of India",
			title: "e₹: cash, but digital",
			items: [{ title: "Retail + wholesale e₹", detail: "RBI still labels the programmes as pilots, including programmability and offline-use exploration.", status: "pilot", sourceId: "rbi-cbdc" }],
			notes: notes(
				"CBDC must not be simplified to public cryptocurrency or proof that all CBDCs use public blockchain.",
				"Different projects can share an idea while sitting at very different maturity stages.",
			),
		},
		{
			id: "finance-maturity",
			kind: "demo",
			demoId: "industry-reality",
			section: "finance",
			sectionLabel: "Finance",
			durationSeconds: 90,
			title: "WHAT IS ACTUALLY LIVE IN 2026?",
			callout: "Production ≠ pilot ≠ prototype ≠ prelaunch ≠ closed",
			sourceIds: ["kinexys", "rbi-cbdc", "bis-agora", "dtcc-tokenization", "india-live-chains", "india-nbf", "walmart-traceability", "tradelens-closure", "google-ap2", "coinbase-x402"],
			notes: notes(
				"A founder does not sell a prototype as production. Click each sector and make the audience separate evidence from hype. The maturity label tells us how much scale, governance, regulation and repeatable value have actually been proven.",
				"Now move from value to physical products and test the same architecture rule.",
				"Which is the stronger engineering signal: a promising demo or a boring system processing value every day?",
				"Repeatable production usage with governance and operations.",
			),
		},
		{
			id: "medicine-journey",
			kind: "demo",
			demoId: "supply-chain",
			section: "supply-chain",
			sectionLabel: "Supply Chain",
			durationSeconds: 120,
			title: "FOLLOW BATCH PCM-001",
			callout: "Manufacturer → Distributor → Warehouse → Hospital → Patient",
			notes: notes(
				"The blockchain does not move the medicine. It helps participants verify the recorded journey.",
				"A useful trace record needs more than a product name.",
			),
		},
		{
			id: "trace-record",
			kind: "cards",
			section: "supply-chain",
			sectionLabel: "Supply Chain",
			durationSeconds: 90,
			title: "A traceable event",
			items: [
				{ title: "Batch ID", detail: "Which physical lot?" },
				{ title: "Actor", detail: "Who submitted it?" },
				{ title: "Time", detail: "When did custody change?" },
				{ title: "Quantity", detail: "What amount moved?" },
				{ title: "Status", detail: "What was verified?" },
				{ title: "Previous event", detail: "Where did it come from?" },
			],
			callout: "Garbage in, immutable garbage out remains possible.",
			notes: notes(
				"Sensors, barcodes, identity controls and audits connect digital history to the physical item.",
				"India has a live government example in this domain.",
			),
		},
		{
			id: "india-drug-logistics",
			kind: "sources",
			section: "supply-chain",
			sectionLabel: "Supply Chain",
			durationSeconds: 75,
			eyebrow: "Live chain · India",
			title: "Drug Logistics Chain",
			items: [{ title: "Procurement → warehouse → hospital", detail: "The NIC portal lists Drug Logistics among its live chains and separately labels other initiatives as POCs.", status: "production", sourceId: "india-live-chains" }],
			notes: notes(
				"The official portal's labels let us discuss a live chain without inflating every government idea into production.",
				"Technology can work and still fail as an ecosystem.",
			),
		},
		{
			id: "supply-chain-lessons",
			kind: "sources",
			section: "supply-chain",
			sectionLabel: "Supply Chain",
			durationSeconds: 75,
			title: "Technology is only half the system",
			items: [
				{ title: "Walmart", detail: "Documented traceability deployment after successful pilots", status: "deployment", sourceId: "walmart-traceability" },
				{ title: "TradeLens", detail: "Technically viable; closed after insufficient collaboration and commercial viability", status: "closed", sourceId: "tradelens-closure" },
			],
			notes: notes(
				"TradeLens teaches the enterprise lesson: governance, incentives, adoption and business viability matter as much as code.",
				"India's national approach is to make common infrastructure available.",
			),
		},
		{
			id: "vishvasya",
			kind: "sources",
			section: "beyond",
			sectionLabel: "Beyond",
			durationSeconds: 60,
			eyebrow: "Production infrastructure · India",
			title: "VISHVASYA",
			items: [{ title: "Permissioned Blockchain-as-a-Service", detail: "A geographically distributed government platform for citizen-centric applications.", status: "production", sourceId: "india-nbf" }],
			notes: notes(
				"MeitY launched Vishvasya in September 2024 across NIC data-centre locations.",
				"The platform becomes meaningful when departments and records use it.",
			),
		},
		{
			id: "india-live-vs-poc",
			kind: "sources",
			section: "beyond",
			sectionLabel: "Beyond",
			durationSeconds: 60,
			title: "LIVE IS NOT THE SAME AS POC",
			items: [
				{ title: "Live chains", detail: "Certificates · documents · drug logistics · property · judiciary · ICJS", status: "production", sourceId: "india-live-chains" },
				{ title: "Proofs of concept", detail: "Assam land · blood bank · GST · PDS", status: "poc", sourceId: "india-live-chains" },
			],
			notes: notes(
				"Preserve the official labels rather than turning promising experiments into deployment claims.",
				"One live use case is relatable to every student: certificates.",
			),
		},
		{
			id: "certificate-chain",
			kind: "sources",
			section: "beyond",
			sectionLabel: "Beyond",
			durationSeconds: 60,
			eyebrow: "Production · CBSE",
			title: "Verify the credential, not a photocopy",
			items: [{ title: "Issuer → hashed record → verifier", detail: "NIC states that CBSE academic documents for 2019–2021 are stored on-chain and available for verification.", status: "production", sourceId: "india-cbse" }],
			notes: notes(
				"Students avoid repeated proof, institutions reduce verification work, and employers gain confidence.",
				"The same idea extends across domains inside conventional enterprise applications.",
			),
		},
		{
			id: "ai-blockchain-convergence",
			kind: "demo",
			demoId: "ai-convergence",
			section: "beyond",
			sectionLabel: "AI × Blockchain",
			durationSeconds: 180,
			title: "AI ACTS. BLOCKCHAIN PROVES.",
			callout: "An emerging machine-to-machine pattern: reason → authorize → pay → verify",
			sourceIds: ["google-ap2", "coinbase-x402"],
			notes: notes(
				"AI is probabilistic: it can understand intent and choose actions. Deterministic payment and ledger rails can enforce authorization, settle value and preserve a verifiable receipt. In 2026 Google donated AP2 to the FIDO Alliance, while x402 defines an open HTTP payment flow. These are different projects—not proof that every agent needs blockchain—but both expose the new engineering problem: how autonomous software receives limited authority and proves what it did.",
				"This convergence explains why systems skills—not one framework—create career value.",
				"Should an AI agent receive unlimited wallet authority?",
				"No. Use scoped limits, human-approved intent, secure keys, audit logs and recovery paths.",
			),
		},
		{
			id: "why-premium-engineers",
			kind: "cards",
			section: "career",
			sectionLabel: "Career",
			durationSeconds: 150,
			title: "WHY CAN THE SKILL COMMAND A PREMIUM?",
			items: [
				{ title: "Rare intersection", detail: "Distributed systems + security + cryptography + finance" },
				{ title: "Real value at risk", detail: "A small bug can expose money, identity or shared records" },
				{ title: "Hard to reverse", detail: "Deployed contracts and protocols demand careful engineering" },
				{ title: "Production ownership", detail: "Nodes, keys, observability, upgrades and incident response" },
				{ title: "Business translation", detail: "Engineers must explain governance, regulation and tradeoffs" },
				{ title: "AI-era systems", detail: "Agents need secure identity, authorization, payment and proof" },
			],
			callout: "Premium pay follows scarce systems judgment—not merely knowing Solidity.",
			sourceIds: ["wef-future-jobs", "electric-developers", "google-ap2", "coinbase-x402"],
			notes: notes(
				"Avoid promising a salary or guaranteed job. WEF places FinTech engineering, AI/ML and software development among fast-growing roles; Electric Capital reports India onboarded the most new crypto developers in 2024. The defensible message is that cross-domain production competence is scarce and high-stakes.",
				"Turn that into a first-year learning path and a portfolio project.",
				"Which card is hardest to learn from a tutorial alone?",
				"Production ownership and business translation require practice in real systems.",
			),
		},
		{
			id: "build-challenge",
			kind: "cards",
			section: "career",
			sectionLabel: "Career",
			durationSeconds: 180,
			eyebrow: "BCA Year 1 · learn in this order",
			title: "YOUR ROADMAP STARTS NOW",
			items: [
				{ title: "01 · Code", detail: "JavaScript/TypeScript or Python, Git and data structures" },
				{ title: "02 · Systems", detail: "Databases, HTTP, networks, Linux and cloud basics" },
				{ title: "03 · Security", detail: "Hashes, signatures, keys, authentication and threat models" },
				{ title: "04 · Blockchain", detail: "Build a local chain, then learn wallets and smart contracts" },
				{ title: "05 · AI", detail: "Add an agent that proposes an action under explicit policy limits" },
				{ title: "06 · Explain", detail: "Diagram tradeoffs and say when a database is better" },
			],
			callout: "First portfolio: hash → link → tamper → verify → AI proposes → human approves",
			notes: notes(
				"Do not begin with token trading. Begin with programming and systems, build this lecture's chain locally, then add a tiny AI assistant that can only propose—not autonomously execute—an update.",
				"Remember the four engineering truths from today.",
			),
		},
		{
			id: "four-truths",
			kind: "cards",
			section: "closing",
			sectionLabel: "Closing",
			durationSeconds: 90,
			title: "FOUR THINGS TO REMEMBER",
			items: [
				{ title: "Shared history", detail: "Multiple parties see common state" },
				{ title: "Tamper-evident links", detail: "Hashes expose hidden changes" },
				{ title: "Agreement rules", detail: "Networks decide valid state" },
				{ title: "Use only when it fits", detail: "Simpler architecture often wins" },
			],
			sourceIds: ["nist-blockchain", "nist-fit"],
			notes: notes(
				"Blockchain coordinates shared history. Hashes expose changes. Networks need agreement rules. Architecture must fit the problem.",
				"You now understand enough to build, break and question your first version.",
			),
		},
		{
			id: "final-challenge",
			kind: "hero",
			section: "closing",
			sectionLabel: "Closing",
			durationSeconds: 75,
			title: "THE NEXT TECHNOLOGY YOU BUILD",
			lines: ["DOESN'T EXIST YET.", "BUILD → EXPERIMENT → BREAK → LEARN → BUILD AGAIN"],
			callout: "If you could put one real-world shared-history problem on blockchain, what would you build?",
			notes: notes(
				"You are not too early, and you are not too young. Start small, test assumptions, and be willing to conclude that a simpler architecture is better.",
				"Invite two student ideas, then open the room for questions.",
			),
		},
	],
};
