import type { BlogDiagram } from "@/components/marketing/blog-architecture-flow";

export const diagramsData: Record<string, BlogDiagram> = {
  "full-system-topology": {
    title: "Full System Topology",
    summary: "Dynamic edge-to-local request routing. Cloudflare Tunnel proxies HTTPS requests to the private macOS FastAPI server, which validates requests and forwards them to local Ollama.",
    nodes: [
      {
        id: "website",
        label: "Next.js UI & Clients",
        role: "Client Endpoint",
        detail: "Exposes chatbot surfaces and developer integrations calling the OpenAI proxy.",
        layer: "Public Surface",
        kind: "client",
      },
      {
        id: "sdk",
        label: "OpenAI SDK Apps",
        role: "Integration Layer",
        detail: "Third-party scripts, agents, and applications querying the /v1 endpoints.",
        layer: "Public Surface",
        kind: "client",
      },
      {
        id: "dns",
        label: "Cloudflare DNS",
        role: "Edge Routing",
        detail: "DNS nameservers routing domain request traffic through WAF rules.",
        layer: "Cloudflare Edge",
        kind: "approval",
      },
      {
        id: "tunnel",
        label: "Cloudflare Tunnel",
        role: "Secure Ingress",
        detail: "Maintains a secure outgoing link mapping local port 8000 without inbound ports.",
        layer: "Cloudflare Edge",
        kind: "approval",
      },
      {
        id: "gateway",
        label: "FastAPI Gateway",
        role: "Control Plane",
        detail: "FastAPI server checking API key records and queueing concurrent request limits.",
        layer: "macOS AI Server",
        kind: "runtime",
      },
      {
        id: "pg",
        label: "PostgreSQL 17",
        role: "Metadata Store",
        detail: "Relational store containing key hashes and recording request usage logs.",
        layer: "Local Data Plane",
        kind: "data",
      },
      {
        id: "ollama",
        label: "Ollama 0.30.6",
        role: "Model Runtime",
        detail: "Darwin service hosting qwen3.5:9b in memory with flash attention enabled.",
        layer: "Local Data Plane",
        kind: "commit",
      },
    ],
    edges: [
      { source: "website", target: "sdk", label: "chat calls" },
      { source: "sdk", target: "dns", label: "HTTPS requests" },
      { source: "dns", target: "tunnel", label: "edge tunnel" },
      { source: "tunnel", target: "gateway", label: "localhost:8000" },
      { source: "gateway", target: "pg", label: "key checks" },
      { source: "gateway", target: "ollama", label: "Ollama client" },
    ],
  },
  "runtime-boundaries": {
    title: "Runtime Boundaries",
    summary: "Isolation and scope boundaries between client environments, FastAPI control engines, and model runtime settings.",
    nodes: [
      {
        id: "ui",
        label: "Astra UI / Scripts",
        role: "Client Surface",
        detail: "Originates prompts, session ids, and carries bearer credentials.",
        layer: "Client Boundary",
        kind: "client",
      },
      {
        id: "auth",
        label: "Auth Dependency",
        role: "Verification",
        detail: "Intercepts requests and checks X-API-Key hashes against database records.",
        layer: "Gateway Boundary",
        kind: "approval",
      },
      {
        id: "limiter",
        label: "Concurrency Limiter",
        role: "Backpressure",
        detail: "Maintains a BoundedSemaphore of 10 concurrent chat slots to protect memory.",
        layer: "Gateway Boundary",
        kind: "runtime",
      },
      {
        id: "openai-client",
        label: "AsyncOpenAI client",
        role: "Client Adapter",
        detail: "Translates gateway payloads into Ollama OpenAI-compatible calls.",
        layer: "Provider Boundary",
        kind: "runtime",
      },
      {
        id: "ollama-v1",
        label: "Ollama /v1",
        role: "API Endpoint",
        detail: "Upstream port 11434 serving model completions.",
        layer: "Provider Boundary",
        kind: "data",
      },
      {
        id: "model",
        label: "qwen3.5:9b",
        role: "Loaded weights",
        detail: "Runs in GPU memory, warm and persistent using keep_alive=-1.",
        layer: "Model Runtime",
        kind: "commit",
      },
    ],
    edges: [
      { source: "ui", target: "auth", label: "bearer token" },
      { source: "auth", target: "limiter", label: "authorized" },
      { source: "limiter", target: "openai-client", label: "slot acquired" },
      { source: "openai-client", target: "ollama-v1", label: "HTTP forward" },
      { source: "ollama-v1", target: "model", label: "generate" },
    ],
  },
  "concurrency-backpressure": {
    title: "Concurrency and Backpressure",
    summary: "How requests are bounded at the gateway level. Out-of-slot requests fail cleanly and quickly instead of queuing inside Ollama.",
    nodes: [
      {
        id: "callers",
        label: "Concurrent Clients",
        role: "Inbound Load",
        detail: "Multiple application threads calling chat completion endpoints.",
        layer: "Ingress",
        kind: "client",
      },
      {
        id: "semaphore",
        label: "Async Semaphore",
        role: "Slot Gating",
        detail: "Allows exactly 10 slots. If a slot isn't acquired in 0.25s, it overflows.",
        layer: "FastAPI Limiter",
        kind: "approval",
      },
      {
        id: "overflow",
        label: "429 Error Gate",
        role: "Clean Rejection",
        detail: "Returns an OpenAI-compatible 429 rate limit payload to client queues.",
        layer: "FastAPI Limiter",
        kind: "commit",
      },
      {
        id: "ollama-queue",
        label: "Ollama Request Queue",
        role: "Upstream Serving",
        detail: "Receives a maximum of 10 concurrent requests, keeping execution stable.",
        layer: "Model serving",
        kind: "runtime",
      },
      {
        id: "qwen",
        label: "qwen3.5:9b (n_slots=1)",
        role: "Token Serializer",
        detail: "Model weights process active requests in a serialized queue slot.",
        layer: "Model serving",
        kind: "data",
      },
    ],
    edges: [
      { source: "callers", target: "semaphore", label: "10+ calls" },
      { source: "semaphore", target: "overflow", label: "timeout > 0.25s" },
      { source: "semaphore", target: "ollama-queue", label: "slot allocated" },
      { source: "ollama-queue", target: "qwen", label: "token stream" },
    ],
  },
  "unified-memory-model": {
    title: "Unified Memory Model",
    summary: "Division of the 32 GB unified memory on the M1 Pro. Guardrails enforce a single loaded model to protect KV caches and context bounds.",
    nodes: [
      {
        id: "ram",
        label: "32 GB Unified Memory",
        role: "Hardware Pool",
        detail: "Shared memory pool holding system, containers, and model weights.",
        layer: "Hardware Layer",
        kind: "client",
      },
      {
        id: "macos",
        label: "macOS Core & Apps",
        role: "Host OS",
        detail: "Operating system, caching layers, and local workspaces.",
        layer: "Memory Allocations",
        kind: "runtime",
      },
      {
        id: "containers",
        label: "Podman Stack",
        role: "Services",
        detail: "Postgres database, Redis queues, Qdrant indexes, and uvicorn containers.",
        layer: "Memory Allocations",
        kind: "data",
      },
      {
        id: "ollama-cache",
        label: "Ollama Model & Cache",
        role: "Inference Ram",
        detail: "Allocated qwen3.5:9b weights (5.6 GB) and 4096 context KV caches.",
        layer: "Memory Allocations",
        kind: "commit",
      },
      {
        id: "guardrails",
        label: "Memory Guardrails",
        role: "Tuning Config",
        detail: "Max loaded models = 1, context length = 4096, KV cache type = q8_0.",
        layer: "Tuning Controls",
        kind: "approval",
      },
    ],
    edges: [
      { source: "ram", target: "macos", label: "OS share" },
      { source: "ram", target: "containers", label: "Podman allocation" },
      { source: "ram", target: "ollama-cache", label: "GPU unified lease" },
      { source: "guardrails", target: "ollama-cache", label: "caps loading" },
    ],
  },
  "security-control-map": {
    title: "Security Control Map",
    summary: "The layered authentication, edge tunnels, and container boundaries isolating local systems from the public web.",
    nodes: [
      {
        id: "internet",
        label: "Public Callers",
        role: "Unsecured Network",
        detail: "Edge users making request calls over HTTPS networks.",
        layer: "Ingress",
        kind: "client",
      },
      {
        id: "edge",
        label: "Cloudflare Ingress",
        role: "Secure Firewall",
        detail: "Runs WAF filter rules, Zero Trust policies, and terminates public SSL.",
        layer: "Edge security",
        kind: "approval",
      },
      {
        id: "gateway",
        label: "FastAPI Edge",
        role: "API Gateway",
        detail: "Listens on localhost only. Rejects missing keys and unauthorized admin calls.",
        layer: "Control Plane",
        kind: "runtime",
      },
      {
        id: "private-compose",
        label: "Private Compose Network",
        role: "Isolated Network",
        detail: "Binds databases only to internal bridge interfaces, off the web.",
        layer: "Internal Data Plane",
        kind: "data",
      },
      {
        id: "ollama-private",
        label: "Ollama localhost",
        role: "Isolated Engine",
        detail: "Binds exclusively to 127.0.0.1:11434. No public access.",
        layer: "Internal Data Plane",
        kind: "commit",
      },
    ],
    edges: [
      { source: "internet", target: "edge", label: "HTTPS" },
      { source: "edge", target: "gateway", label: "tunnel link" },
      { source: "gateway", target: "private-compose", label: "DB query" },
      { source: "gateway", target: "ollama-private", label: "loopback API" },
    ],
  },
  "dev-vs-production-topology": {
    title: "Dev vs Production Topology",
    summary: "Comparison of environments. Ports, env files, and compose instances are isolated to prevent local developer overlap.",
    nodes: [
      {
        id: "dev-env",
        label: "infra/.env.dev",
        role: "Local Config",
        detail: "Contains development API credentials and development port rules.",
        layer: "Dev Environment",
        kind: "client",
      },
      {
        id: "dev-compose",
        label: "compose.dev.yaml",
        role: "Development Stack",
        detail: "Launches developer container networks on port 8010.",
        layer: "Dev Environment",
        kind: "runtime",
      },
      {
        id: "prod-env",
        label: "infra/.env",
        role: "Production Config",
        detail: "Holds production API hashes, admin secrets, and production keys.",
        layer: "Prod Environment",
        kind: "client",
      },
      {
        id: "prod-compose",
        label: "compose.yaml",
        role: "Production Stack",
        detail: "Starts the production container networks on loopback port 8000.",
        layer: "Prod Environment",
        kind: "runtime",
      },
      {
        id: "tunnel",
        label: "Cloudflare Ingress",
        role: "Tunnel Target",
        detail: "Targets exclusively localhost:8000, isolating the dev stack.",
        layer: "Prod Environment",
        kind: "approval",
      },
    ],
    edges: [
      { source: "dev-env", target: "dev-compose", label: "loads" },
      { source: "prod-env", target: "prod-compose", label: "loads" },
      { source: "prod-compose", target: "tunnel", label: "listens" },
    ],
  },
  "future-rate-limiting": {
    title: "Future Rate Limiting",
    summary: "Planned per-key rate-limiting design, combining edge-based checks with local Redis counter stores.",
    nodes: [
      {
        id: "request",
        label: "Inbound Request",
        role: "Client Call",
        detail: "Enters from public networks requesting completions.",
        layer: "Ingress",
        kind: "client",
      },
      {
        id: "edge-limit",
        label: "Cloudflare Edge limit",
        role: "IP Filtering",
        detail: "Limits request volume by IP and path parameters before the tunnel.",
        layer: "Edge security",
        kind: "approval",
      },
      {
        id: "gateway-auth",
        label: "FastAPI Auth",
        role: "Key Validation",
        detail: "Verifies the key details and retrieves the caller limit profile.",
        layer: "Control Plane",
        kind: "runtime",
      },
      {
        id: "redis-check",
        label: "Redis Per-Key Counter",
        role: "Distributed Ledger",
        detail: "Checks sliding window request counter in Redis database cache.",
        layer: "Rate Limit Storage",
        kind: "data",
      },
      {
        id: "reject",
        label: "429 Error Gate",
        role: "Rate Rejection",
        detail: "Rejects requests with a Retry-After header once limits expire.",
        layer: "Endpoints",
        kind: "commit",
      },
    ],
    edges: [
      { source: "request", target: "edge-limit", label: "edge filter" },
      { source: "edge-limit", target: "gateway-auth", label: "forwarded" },
      { source: "gateway-auth", target: "redis-check", label: "limits check" },
      { source: "redis-check", target: "reject", label: "limit exceeded" },
    ],
  },
};
